const en_US = {
	// 头部导航栏
	'header_analytics': 'Data Analytics',
	'header_inspiration': 'Inspiration',
	'header_global_list': 'Social Top 100',
	'header_dashboard': 'Manager’s Dashboard',
	'header_insight': 'Insight',
	'header_tools': 'Growth Tools',
	'header_diagnosis': 'Diagnosis',
	'header_my_material': 'My Library',
	'header_FAQ': 'FAQ',
	'header_os_Rating': 'OS Rating',
	'header_my_message': 'Messages',
	'header_my_info': 'Info',
	'header_wechat_service': 'Wechat Service',
	'header_exit': 'Logout',
	// 分析-平台导航区
	'pfnav_choose_platform': 'Select Platform:',
    'pfnav_facebook_homepage_list': 'Facebook  Analytics',
    'pfnav_twitter_homepage_list': 'Twitter Analytics',
	'pfnav_instagram_homepage_list': 'Instagram Analytics',
	'pfnav_linked_homepage_list': 'LinkedIn Analytics',
	'pfnav_youtube_homepage_list': 'YouTube Analytics',
    'pfnav_my_homepage_list': 'My Pages List',
    'pfnav_browse_by_brand': 'Browse by Brand',
    'pfnav_browse_by_country': 'Browse by Country',
    'pfnav_browse_by_color': 'Browse by Tag',
    'pfnav_homepage_detail': 'Page Details',
	'pfnav_post_detail': 'Post Details',
	'pfnav_addpage': 'Add Page',
	// 分析-列表区
	'pagetable_analytics': 'Data Analytics',	
	'pagetable_thead_homepage':'Pages',
	'pagetable_thead_brand':'Brand',
	'pagetable_thead_country':'Country/Region',
	'pagetable_thead_grade':'OS Rank',
	'pagetable_thead_fans':'Fans',
	'pagetable_thead_posts': 'Posts',
	'pagetable_thead_addfans':'New Add Fans',//不在列表中
	'pagetable_thead_jobvacancy':'Job Openings',
	'pagetable_thead_online':'Employees',
	'pagetable_thead_subscriber':'Subscribers',
	'pagetable_thead_postvideos':'Videos',
	'facebook_thead_active_engagement':'Engagement',
	'facebook_thead_active_mood':'Reactions',
	'facebook_thead_active_share':'Shares',
	'facebook_thead_active_comment':'Comments',
	'twitter_thead_active_engagement':'Engagement',
	'twitter_thead_active_like':'Likes',
	'twitter_thead_active_transpond':'Retweets',
	'twitter_thead_active_reply':'Replies',
	'ins_thead_active_engagement':'Engagement',
	'ins_thead_active_givelike':'Like',
	'ins_thead_active_comment':'Comment',
	'facebook_thead_topic_text':'Text',
	'facebook_thead_topic_picture':'Photo',
	'facebook_thead_topic_video':'Video',
	'facebook_thead_topic_link':'Link',
	'facebook_thead_topic':'Posts',
	'facebook_thead_topic_other':'Other',
	'twitter_thead_topic_text':'Text',
	'twitter_thead_topic_picture':'Photo',
	'twitter_thead_topic_video':'Video',
	'twitter_thead_topic':'Posts',
	'ins_thead_topic_picture':'Photo',
	'ins_thead_topic_video':'Video',
	'ins_thead_topic_slide':'Carousel',
	'ins_thead_topic':'Posts',
	'pagetable_thead_more_operate':'Setting',
	'page_first_load_tip': 'Your page data is loading, please come back and check later.',
	// 分析-标签管理
	'title_current_tags':'Current Tags',
	'title_add_tags':'Add Tags',
	'input_new_tag':'Enter New Tag',
	'btn_add_tag':'Add',
	'btn_tag_sure':'OK',
	'add_tag_warn_only12':'Limited to 12 characters',
	'add_tag_warn_repeat':'Tags cannot be duplicated',
	'add_tag_warn_max3':'Limited to 3 tags',
	'page_no_tags_left':'Add a tag for ',
	'page_no_tags_right':' ',
	'chose_alltags':'All Pages',
	'chose_notags':'No Tags',
	'select_tags':'Select Tags',
	// 分析-添加页面 AddPage
	'add_page_ins_tips':'Failure to add Instagram Page? Click here to get more about how to switch a personal page to business page.',
	'add_page_please_add': 'Select in Industry',
	'add_page_add_homepage_to_my_list': 'Add Pages to My List',
	'add_linkedInpage_add_homepage_to_my_list': 'Add LinkedIn homepage to my list',
	'add_linkedInpage_prompt': 'Free users can add 2 brand homepages and enter links to join the list.',
    'add_page_choose_long_term_concern': 'Chose the brand that you care about, then click add button to your Page List.',
	'add_page_search_by_brand': 'Search by Brand',
	'add_page_search_by_link': 'Search by Link',
	'add_page_search_by_industry': 'Search by Industry',
	'add_page_choose_one_level_industry': 'Select 1st-Class Industry',
	'add_page_admin_add_multiple_pages': 'I\'m Admin, Connect Facebook to Add Multiple Pages.',
	'add_page_recent_popular_pages': 'Recent Popular Pages',
	'add_page_notfound_this_homepage': 'We didn\'t find the page. Please confirm your Page link.',
	'add_page_unable_get_valid_page_link': 'Unable to get a valid page\'s link? ',
	'add_page_click_here': 'Click here',
	'add_page_learn_more': 'to learn more.',
	'add_paged_add': 'Add',
	'add_paged_added': 'Added',
	// 分析-主页详情-头部
	'pagedetail_tag':'Tags',
	'pagedetail_alias': 'Alias',
	'pagedetail_null': 'Null',
	'pagedetail_summary': 'About',
	'pagedetail_add_to_pagelist': '+ Add to my page list',
	'pagedetail_adding_to_pagelist': 'Adding...',
	'pagedetail_added_to_pagelist': 'Added to my list',
	'pagedetail_clerk': 'Employees',
	// 分析-主页详情-总览
	'pagedetail_pandect': 'OverView',
	'pagedetail_title_admin':'I’m Admin,',
	'pagedetail_title_auth':' connect ',
	'pagedetail_title_getmoredata':' insights.',
	'pagedetail_postoverview':'Post overview',
	'pagedetail_postGood':'Best post',
	'pagedetail_postlow':'Worst post',
	'pagedetail_postlist':'Post List',
	'pagedetail_impression':'Posts Impressions',
	'pagedetail_click':'Posts Clicks',
	'pagedetail_negative':'Posts Negative Feedback',
	'pagedetail_fanverview':'Overview',
	'pagedetail_Fansportrait':'Portrayal analysis',
	'pagedetail_data_overview': 'Data Overview',
	'pagedetail_title_industry': ' Industry',
	'pagedetail_fans_top': 'Fans Top ',
	'pagedetail_growth_of_fans': 'Growth of Fans',
	'pagedetail_posts': 'Posts',
	'pagedetail_compare_front_compare': 'Previous ',
	'pagedetail_compare_front_days': ' days',
	'pagedetail_thousand_interaction': 'Engagement per 1k Fans',
	'pagedetail_single_post_interaction': 'Engagement per Post',
	'pagedetail_top_post_interaction': 'Top Engagement Post',
	'pagedetail_view_top_post': 'Go to Post Details',
	'pagedetail_page_info': 'Page Info',
	'pagedetail_page_id': 'Page ID',
	'pagedetail_page_web': 'Page Web',
	'pagedetail_brand': 'Brand',
	'pagedetail_industry': 'Industry',
	'pagedetail_car': 'Car',
	'pagedetail_target_market': 'Targeting',
	'pagedetail_website': 'Website',
	'pagedetail_page_age': 'Page History',
	'pagedetail_years': 'Years',
	'pagedetail_HQaddress': 'Location',
	'pagedetail_jobVacancy': 'Number of Employees',
	'pagedetail_clerkNumber': 'Employees',
	// 分析-主页详情-帖文
	'pagedetail_post': 'Post',
	'pagedetail_spread': 'All',
	'pagedetail_collect_post': 'Favorite',
	'pagedetail_collect_video': 'Favorite',
	'pagedetail_collected': 'Favorited',
	'pagedetail_post_engagement': 'Engagement',
	'pagedetail_post_mood': 'Reactions',
	'pagedetail_post_share': 'Shares',
	'pagedetail_post_comment': 'Comments',
	'pagedetail_post_like': 'Likes',
	'pagedetail_post_transpond': 'Retweets',
	'pagedetail_post_reply': 'Replies',
	'pagedetail_post_linkedlike': 'Likes',
	'pagedetail_post_comments': 'Comments',
	'pagedetail_post_and_post_engagement': 'Posts and Engagements',
	'pagedetail_trend_table_line_SumPost':'Total Posts',
	'pagedetail_trend_table_line_MaxPost':'Max Posts of the day',
	'pagedetail_trend_table_line_MinPost':'Min Posts of the day',
	'pagedetail_trend_table_line_AvgPost':'Avg Posts per day',
	'pagedetail_trend_table_line_SumEngagement':'Total engagement of the day',
	'pagedetail_trend_table_line_MaxEngagement':'Max engagement of the day',
	'pagedetail_trend_table_line_MinEngagement':'Min engagement of the day',
	'pagedetail_trend_table_line_AvgEngagement':'Avg engagement per day',
	'pagedetail_post_num_by_type':'Posts by Type',
	'pagedetail_post_type': 'Type',
	'pagedetail_post_num': 'Count',
	'pagedetail_post_num_ratio': 'Share',
	'pagedetail_photo':'Photos',
	'pagedetail_video':'Videos',
	'pagedetail_status':'Texts',
	'pagedetail_link':'Links',
	'pagedetail_other':'Others',
	'pagedetail_post_list': 'Posts List',
	'pagedetail_post_time': 'Time',
	'pagedetail_post_content': 'Content',
	'pagedetail_post_collect': 'Favorite',
	'pagedetail_type': 'Type',
	'pagedetail_click_show_more': 'More',
	'pagedetail_post_list_tip': 'The post time (UTC +00:00) was switched to your local timezone automatically. Ex. in China, the post time have added +8h (UTC +08:00).',
	// 分析-主页详情-粉丝
	'pagedetail_fan': 'Fan',
	'pagedetail_chart_title_Fans': 'Total Fans',
	'pagedetail_trend_table_line_CurrentFansNum':'Current Fans',
	'pagedetail_trend_table_line_MaxPerDayFansNum':'Max Fans',
	'pagedetail_trend_table_line_MinPerDayFansNum':'Min Fans',
	'pagedetail_chart_title_FansGrowth': 'Number of Growth of Fans',
	'pagedetail_trend_table_line_TotalFansNum':'Total Change of Fans',
	'pagedetail_trend_table_line_MaxPerDayFansGrowthNum':'Max Change of Fans',
	'pagedetail_trend_table_line_MinPerDayFansGrowthNum':'Min Change of Fans',
	'pagedetail_trend_table_line_AvgPerDayFansGrowthNum':'Avg Change of Fans',	
	'pagedetail_trend_table_line_FansGrowthType':'Number of Growth of Fans by Type',
	'pagedetail_trend_table_line_AgainUseAccount':'Restored Likes from Reactivated Accounts',
	'pagedetail_trend_table_line_DynamicMessage':'News Feed',
	'pagedetail_trend_table_line_YourHomePage':'Your Page',
	'pagedetail_chart_title_FansDecrease': 'Number of Decrease of Fans',
	'pagedetail_trend_table_line_TotalFansDecreaseNum':'Total Decrease os Fans',
	'pagedetail_trend_table_line_MaxPerDayFansDecreaseNum':'Max Decrease of Fans',
	'pagedetail_trend_table_line_MinPerDayFansDecreaseNum':'Min Decrease of Fans',
	'pagedetail_trend_table_line_AvgPerDayFansDecreaseNum':'Avg Decrease of Fans',
	'pagedetail_chart_title_FansDecreaseType': 'Number of Decrease of Fans by Type',
	'pagedetail_trend_table_line_RemoveInvalidAccount':'Deactivated or Memorialized Account Removals',
	'pagedetail_trend_table_line_CancelPagePraise':'Unlikes From Page, Posts, or News Feed',
	'pagedetail_trend_table_line_FansDecreaseOther':'Other',
	'pagedetail_chart_title_FansTime':'Fans Online Time',
	'pagedetail_chart_title_FansGrowthAndPostEngagement': 'Growth of Fans and Engagement',
	'pagedetail_trend_table_line_MaxFansChange':'Max Change of Fans',
	'pagedetail_trend_table_line_MaxFansChangeCurrentDayEngagement':'Total engagement on Max Change Day',
	'pagedetail_trend_table_line_PostEngagement': 'Engagement',
	'pagedetail_fansTable_title_rank':"Rank",
	'pagedetail_fansTable_title_country':"Country",
	'pagedetail_fansTable_title_impressions':"Impressions Reach People",
	'pagedetail_fansTable_title_impressions_percentage':"Share",
	'pagedetail_fansTable_title_growth_rate':"Growth Rate",
	'pagedetail_fansTable_title_fans_count_lifetime':"Local Fans",
	'pagedetail_fansTable_title_percentage':"Share",
	'pagedetail_fansTable_title_fans_diff':"Total Growth of Fans",
	//粉丝时间Y轴星期
	'PageDetail_fantime_Sunday':'Sun',
	'PageDetail_fantime_Monday':'Mon',
	'PageDetail_fantime_Tuesday':'Tue',
	'PageDetail_fantime_Wednesday':'Wed',
	'PageDetail_fantime_Thursday':'Thu',
	'PageDetail_fantime_Friday':'Fri',
	'PageDetail_fantime_Saturday':'Sat',
	// 分析-主页详情-粉丝-悬浮框
	'tooltip_fans': 'The total number of Page\'s fans, who liked your Page, during a selected time range.',
	'tooltip_fans_growth': 'The number of growth of fans, during a selected time range.',
	'tooltip_fans_growth_by_type': 'The number of growth of fans, broken down by people like sources, during a selected time range.',
	'tooltip_fans_decrease': 'The number of people who unlikes of your Page, during a selected time range.',
	'tooltip_fans_decrease_by_type': 'The number of people who unlikes of your Page, broken down by people unlike sources, during a selected time range.',
	'tooltip_fans_growth_and_post_engagement': 'The relevance between Growth of Fans and Engagements, during a selected time range.',
	'tooltip_fansTime': 'The number of page fans who saw any posts on Facebook on a given day, during a selected time range.',
	// 分析-主页详情-粉丝-右侧tip
	'tip_fans': 'The total number of Page\'s fans, who liked your Page.',
	'tip_fans_growth': 'The number of growth of fans.',
	'tip_fans_growth_by_type': 'The number of growth of fans, broken down by people like sources.',
	'tip_fans_decrease': 'The number of people who unlikes of your Page.',
	'tip_fans_decrease_by_type': 'The number of people who unlikes of your Page, broken down by people unlike sources.',
	'tip_fans_growth_and_post_engagement': 'The relevance between Growth of Fans and Engagements.',
	'tip_fansTime': 'The number of page fans who saw any posts on Facebook on a given day.',
	// 分析-主页详情-互动
	'pagedetail_engagement': 'Engagement',
	'pagedetail_interaction': 'Interaction',
	'pagedetail_chart_title_PostEngagementByType':'Number of engagement by Type',
	'pagedetail_chart_title_ThsEngagementByType':'Number of engagements per 1k Fans',
	'pagedetail_chart_title_SingleEngagement':'Average engagement per Post',
	'pagedetail_chart_title_PositiveOperatorNum': 'Page Positive Feedback by Type',
	'pagedetail_trend_table_line_AnswerUserQuestion':'Answer',
	'pagedetail_trend_table_line_Link':'Link',
	'pagedetail_trend_table_line_Mood':'Like',
	'pagedetail_chart_title_NegativeOperatorNum': 'Page Negative Feedback by Type',
	'pagedetail_trend_table_line_HideAllPosts':'Hide All Clicks',
	'pagedetail_trend_table_line_ClosePage':'Xbutton Clicks',
	'pagedetail_trend_table_line_ReportJunkInfo':'Report Spam Clicks',
	'pagedetail_chart_title_PostEngagementRatio': 'Proportion of Engagement',
	'pagedetail_chart_title_MoodRatio': 'Proportion of Reactions',
	'pagedetail_chart_title_PageClickNumRatio': 'Proportion of Page Consumptions',
	'pagedetail_chart_title_PositiveOperatorRatio': 'Proportion of Page Positive Feedback',
	'pagedetail_chart_title_NegativeOperatorRatio': 'Proportion of Page Negative Feedback',
	// 分析-主页详情-互动-悬浮框
	'tooltip_post_engagement_by_type': 'The number of engagement  (Reactions + Comments + Shares), during a selected time range.',
	'tooltip_tw_post_engagement_by_type': 'The number of engagement  (Likes + Replies + Retweets), during a selected time range.',
	'tooltip_ins_post_engagement_by_type': 'The number of engagement  (Likes + Comments), during a selected time range.',
	'tooltip_thousand_fans_engagement': 'The average number of engagements per 1, 000 fans (the sum of engagements/the number of total fans*1000), during a selected time range.（Sum engagement per 1k Fans: The sum of everyday engagement per 1k fans during a selected time range.）',
	'tooltip_single_post_engagement': 'The average number of engagement per post (=the sum of engagement per day / the sum of posts per day), during a selected time range.',
	'tooltip_positive_operator_num_by_type': 'The number of times people took a positive action broken down by action type, during a selected time range.',
	'tooltip_negative_operator_num_by_type': 'The number of times people took a negative action broken down by action type, during a selected time range.',
	'tooltip_post_engagement_ratio': 'The proportion of each type of engagement (Reactions, Shares, Comments), during a selected time range.',
	'tooltip_mood_ratio': 'The proportion of each type of reactions (Like, Love, Haha, Wow, Sad, Angry), during a selected time range.',
	'tooltip_page_click_num_ratio': 'The proportion of each type of Page\'s content clicks, during a selected time range.',
	'tooltip_positive_operator_ratio': 'The proportion of each type of Page\'s positive feedback, during a selected time range.',
	'tooltip_negative_operator_ratio': 'The proportion of each type of Page\'s negative feedback, during a selected time range.',
	'tooltip_ossScore':'OS Rating is a rating according to your page’s fans, growth of fans, posts, engagement and engagement per 1k fans.',
	'tooltip_insossScore':'OS Rating is a rating according to your page’s fans, growth of fans, posts and engagement',
	'tooltip_post_and_engagement':'The correlation between number of posts and engagements.',
	// 分析-主页详情-互动-右侧tip
	'tip_post_engagement_by_type': 'The number of engagement  (Reactions + Comments + Shares).',
	'tip_tw_post_engagement_by_type': 'The number of engagement  (Likes + Replies + Retweets).',
	'tip_ins_post_engagement_by_type': 'The number of engagement  (Likes + Comments).',
	'tip_thousand_fans_engagement': 'The average number of engagement per 1,000 fans (= the sum of engagement / the number of total fans * 1000).',
	'tip_single_post_engagement': 'The average number of engagement per post (= the sum of engagement / the sum of posts ).',
	'tip_positive_operator_num_by_type': 'The number of times people took a positive action broken down by type.',
	'tip_negative_operator_num_by_type': 'The number of times people took a negative action broken down by type.',
	'tip_post_engagement_ratio': 'The proportion of each type of engagement (Reactions, Shares, Comments).',
	'tip_mood_ratio': 'The proportion of each type of reactions (Like, Love, Haha, Wow, Sad, Angry).',
	'tip_page_click_num_ratio': 'The proportion of each type of Page\'s content clicks.',
	'tip_positive_operator_ratio': 'The proportion of each type of Page\'s positive feedback.',
	'tip_negative_operator_ratio': 'The proportion of each type of Page\'s negative feedback.',
	// 分析-主页详情-曝光
	'pagedetail_exposure': 'Impression',
	'pagedetail_chart_title_PageAndPostExposureNum':'Page Impressions and Post Impressions',
	'pagedetail_trend_table_line_TotalPageExposureNum':'Total Page Impressions',
	'pagedetail_trend_table_line_MaxPerDayPageExposure':'Max Page Impressions',
	'pagedetail_trend_table_line_MinPerDayPageExposure':'Min Page Impressions',
	'pagedetail_trend_table_line_AvgPerDayPageExposure':'Avg Page Impressions',
	'pagedetail_trend_table_line_AvgPageExposureFrequency':'Avg Page Impressions Frequency',
	'pagedetail_trend_table_line_TotalPostExposureNum':'Total Post Impressions',
	'pagedetail_trend_table_line_MaxPerDayPostExposure':'Max Post Impressions',
	'pagedetail_trend_table_line_MinPerDayPostExposure':'Min Post Impressions',
	'pagedetail_trend_table_line_AvgPerDayPostExposure':'Avg Post Impressions',
	'pagedetail_trend_table_line_AvgPostExposureFrequency':'Avg Post Impressions Frequency',
	'pagedetail_chart_title_PageExposureNumRatio':'Proportion of Page Impressions',
	'pagedetail_chart_title_PostExposureNumRatio':'Proportion of Post Impressions',
	'pagedetail_chart_title_PageExposureNumOfPeopleDistribution':'Page Impressions by Country',
	// 分析-主页详情-曝光-悬浮框
	'tooltip_PageAndPostExposureNum':"The impressions and promotion effectiveness of your page and your posts.(Page Impressions:The number of times any content from your Page or about your Page entered a person's screen, ex:check-ins, ads and more. Post Impressions:The number of times your Page's post entered a person's screen, ex: statuses, photos, videos and more.",
	'tooltip_PageExposureNumRatio':'The proportion of Paid Page impressions and Organic Page impressions, during a selected time range.',
	'tooltip_PostExposureNumRatio':'The proportion of Paid post impressions and Organic post impressions, during a selected time range.',
	'tooltip_PageExposureNumOfPeopleDistribution':'The number of people who have seen any content associated with your Page broken down by country, during a sleected time range.',
	'tooltip_post_impressions':'Post Impressions',
	'tooltip_page_impressions':'Page Impressions',
	// 分析-主页详情-曝光-右侧tip
	'tip_PageAndPostExposureNum':'The impressions and promotion effectiveness of your page and your posts.',
	'tip_PageExposureNumRatio':'The proportion of Paid Page impressions and Organic Page impressions.',
	'tip_PostExposureNumRatio':'The proportion of Paid post impressions and Organic post impressions.',
	'tip_PageExposureNumOfPeopleDistribution':'The number of people who have seen any content associated with your Page broken down by country.',
	// 分析-主页详情-视频
	'pagedetail_video': 'Video',
	'pagedetail_chart_title_post_video_time_watched':'Length of Post Video View',
	'pagedetail_chart_title_Video_Views':'Post Video View Times',
	'pagedetail_chart_title_Video_Proportion':'Proportion of Post Video View Times',
	'pagedetail_chart_title_VideoWatchTimesFunnel':'Funnel of Post Video View Times',
	'pagedetail_chart_title_VideoPlayRatio':'Proportion of Post Video Played Operation',
	'pagedetail_trend_table_line_VideoTimeSum':'Total Length of Video View',
	'pagedetail_trend_table_line_VideoTimeMax':'Max Length of Video View',
	'pagedetail_trend_table_line_VideoTimeMin':'Min Length of Video View',
	'pagedetail_trend_table_line_VideoTimeAvg':'Avg Length of Video View',
	'pagedetail_trend_table_line_VideoViewsSum':'Total Video View Times',	
	'pagedetail_trend_table_line_VideoViewsMax':'Max Video View Times',
	'pagedetail_trend_table_line_VideoViewsMin':'Min Video View Times',
	'pagedetail_trend_table_line_VideoViewsAvg':'Avg Video View Times',
	// 分析-主页详情-视频-悬浮框
	'tooltip_post_video_time_watched': 'The total time of people viewed Page\'s video, during a selected time range.',
	'tooltip_Video_Views': 'The total time of people viewed Page\'s video.',
	'tooltip_Video_Proportion': 'The proportion of Paid post video view times and Organic post video view times, during a selected time range.',
	'tooltip_VideoWatchTimesFunnel': 'The retention rate of Paid post video view times and Organic post video view times, during a selected time range.',
	'tooltip_VideoPlayRatio': 'The proportion of Auto-played and Click to Play video views on your Page, during a selected time range.',
	'tooltip_page_video_views_organic':'Organic Video View Times',
	'tooltip_page_video_views_paid':'Paid Video View Times',
	'tooltip_page_video_views_autoplayed':'Autoplay',
	'tooltip_page_video_views_click_to_play':'Click to Play',
	// 分析-主页详情-视频-右侧tip
	'tip_post_video_time_watched': 'The total time of people viewed Page\'s video.',
	'tip_Video_Views': 'The number of times your Page\'s videos played for at least 3 seconds, or for nearly their total length if they\'re shorter than 3 seconds.',
	'tip_Video_Proportion': 'The proportion of Paid post video view times and Organic post video view times.',
	'tip_VideoWatchTimesFunnel': 'The retention rate of Paid post video view times and Organic post video view times.',
	'tip_VideoPlayRatio': 'The proportion of Auto-played and Click to Play video views on your Page.',
	// 分析-主页详情-粉丝画像
	'pagedetail_fans_portrait': 'Fans Portrayal',
	'pagedetail_chart_title_GenderAndAge':'Gender and Age of Fans',
	'pagedetail_chart_title_FansCountryDistribution': 'Page Fans by Country',
	'pagedetail_chart_title_FansGrowthCountryDistribution': 'Growth of Fans by Country',
	'male': "Male",
	'female': 'Female',
	'a_period_male': 'A Period Male',
	'a_period_female': 'A Period Female',
	'b_period_male': 'B Period Male',
	'b_period_female': 'B Period Female',
	'view_more': 'View More',
	// 分析-主页详情-粉丝画像-悬浮框
	'tooltip_GenderAndAge': 'The aggregated fans data according to the age and gender, during a selected time.',
	'tooltip_FansCountryDistribution': 'The Page fans broken down by country, during a selected time range.',
	'tooltip_FansGrowthCountryDistribution': 'The growth of fans broken down by country, during a selected time range.',
	// 分析-主页详情-粉丝画像-右侧tip
	'tip_GenderAndAge': 'The aggregated fans data according to the age and gender, during a selected time.',
	'tip_FansCountryDistribution': 'The Page fans broken down by country.',
	'tip_FansGrowthCountryDistribution': 'The growth of fans broken down by country.',
	// 分析-主页详情-内容
	'pagedetail_content': 'Content',
	// 分析-主页详情-主页
	'pagedetail_noauth_tip':'Connect with Facebook to get Insights Data',
	'pagedetail_page': 'Page',	
	'pagedetail_trend_table_line_Max':'Max',
	'pagedetail_trend_table_line_Min':'Min',
	'pagedetail_trend_table_line_Avg':'Avg',
	'pagedetail_trend_table_line_Value':'Value',
	'pagedetail_trend_table_line_Maxfans':'Max Fans',
	'pagedetail_trend_table_line_Minfans':'Min Fans',
	'pagedetail_trend_table_line_Avgfans':'Avg Fans',
	'pagedetail_trend_table_line_Maxtopicactive':'Max Engagement per Posts',
	'pagedetail_trend_table_line_Mintopicactive':'Min Engagement per Posts',
	'pagedetail_trend_table_line_Avgtopicactive':'Avg Engagement per Posts',
	'pagedetail_trend_table_line_Maxpagescore':'Max OS Ranking',
	'pagedetail_trend_table_line_Minpagescore':'Min OS Ranking',
	'pagedetail_trend_table_line_Avgpagescore':'Avg OS Ranking',	
	'pagedetail_trend_table_line_SumPostEngagement':'SumEngagement',
	'pagedetail_trend_table_line_MaxPostEngagement':'MaxEngagement',
	'pagedetail_trend_table_line_MinPostEngagement':'MinEngagement',
	'pagedetail_trend_table_line_AvgPostEngagement':'AvgEngagement',
	'pagedetail_trend_table_line_SumThsEngagement':'SumEngagement per 1K Fans',
	'pagedetail_trend_table_line_MaxThsdayEngagement':'MaxEngagement per 1K Fans',
	'pagedetail_trend_table_line_MinThsdayEngagement':'MinEngagement per 1K Fans',
	'pagedetail_trend_table_line_AvgThsdayEngagement':'AvgEngagement per 1K Fans',
	'pagedetail_trend_table_line_SumpreEngagement':'Average No. of engagements per Post of the period',
	'pagedetail_trend_table_line_MaxpredayEngagement':'MaxEngagement per Post',
	'pagedetail_trend_table_line_MinpredayEngagement':'MinEngagement per Post',
	'pagedetail_trend_table_line_AvgpredayEngagement':'AvgEngagement per Post',		
	'pagedetail_trend_table_line_SumBy@':'Total Mentioned',
	'pagedetail_trend_table_line_MaxBy@':'Max Mentioned',
	'pagedetail_trend_table_line_MinBy@':'Min Mentioned',
	'pagedetail_trend_table_line_AvgBy@':'Avg Mentioned',
	'pagedetail_trend_table_line_page_video_views_all':'Video View Times',
	'pagedetail_trend_table_line_page_video_views_10':'10s Video View Times',
	'pagedetail_trend_table_line_page_video_views_30':'30s or Complete Video View Times',
	'pagedetail_chart_title_fans':'fans',
	'pagedetail_chart_title_OSScore':'OS Rating',	
	'pagedetail_chart_title_by@':'Mentioned(@)',
	'pagedetail_chart_title_PostEngagementScale':'Proportion of engagement',
	'pagedetail_chart_title_alltypeEngagement':"Number of engagement of Posts by Post's Type",
	'pagedetail_chart_title_alltypeEngagementbytype':"Proportion of engagement of Posts by Posts's Type",
	'Login_with_facebook':'Continue With Facebook',
	// 分析-主页详情-关注
	'pagedetail_attention': 'Following',
	'pagedetail_chart_title_attention_diff': 'Growth of Following',
	'pagedetail_chart_title_belong_list': 'Member of',
	'pagedetail_trend_table_line_attentionCur':'Current Following',	
	'pagedetail_trend_table_line_attentionMax':'Max Following',	
	'pagedetail_trend_table_line_attentionMin':'Min Following',	
	'pagedetail_trend_table_line_SumAttentionDiff':'Total Growth of Following',
	'pagedetail_trend_table_line_MaxAttentionDiff':'Max Growth of Following',
	'pagedetail_trend_table_line_MinAttentionDiff':'Min Growth of Following',
	'pagedetail_trend_table_line_AvgAttentionDiff':'Avg Growth of Following',
	'pagedetail_trend_table_line_belongListCur':'Current Member of',	
	'pagedetail_trend_table_line_belongListMax':'Max Member of',	
	'pagedetail_trend_table_line_belongListMin':'Min Member of',
	"tooltip_attention":"Tne total number of page's following, during a selected time range.",
	"tip_attention":"Tne total number of page's following.",
	"tooltip_attention_diff":"The number of growth of following, during a selected time range.",
	"tip_attention_diff":"The number of growth of following.",
	"tooltip_belong_list":`The number of page's "member of" list, during a selected time range.`,
	"tip_belong_list":`The number of page's "member of" list.`,
	// INS分析-主页详情-话题
	'pagedetail_topic': 'Hashtag',
	'pagedetail_chart_title_topic_usenum':'Number of Hashtags',
	'pagedetail_trend_table_line_SumTopic':'Total Hashtags',
	'pagedetail_trend_table_line_MaxTopic':'Max Hashtags',
	'pagedetail_trend_table_line_MinTopic':'Min Hashtags',
	'pagedetail_trend_table_line_AvgTopic':'Avg Hashtags',
	'pagedetail_trend_table_topic_cloud':'Hashtags Cloud',	
	'pagedetail_trend_table_topic_ranking':'Rank',	
	'pagedetail_trend_table_topic_usenum':'Used Times',	
	'pagedetail_trend_table_topic_active':'Total Engagement',	
	'pagedetail_trend_table_topic_seemost':'View Max Engagement Post',
	// YouTube-主页详情
	'pagelist_ytb_tip':'There are no engagements due to the 0 growth of video,during the selected time. You could switch the time range to get nearest video.',
	'pagedetail_subscriber_text': 'Subscribers',
	'pagedetail_comment': 'Comments',
	'pagedetail_growth_of_subscriber': 'Growth of Subscribers',
	'pagedetail_growth_of_video': 'Growth of Videos',
	'pagedetail_growth_of_video_view_time': 'Growth of Video Views',
	'pagedetail_single_item_interaction': 'Engagements per Video',
	'pagedetail_top_video_view_time': 'Top Engagements Video Views',
	'pagedetail_view_time': 'Video Views',
	'pagedetail_total_video': 'Total Videos',
	'pagedetail_collect_video': 'Favorite',
	'pagedetail_top': 'Likes',
	'pagedetail_tread': 'Dislikes',
	'pagedetail_chart_title_SubscriberComment':"Subscribers and Video Views ",
	'tip_Ytb_SubscriberComment':"The total number of page's subscribers and number of Video Views.",
	'tooltip_Ytb_SubscriberComment':"The total number of page's subscribers and number of Video Views, during the selected time range.",
	'pagedetail_trend_table_line_MaxSubscriber': 'Max Subscribers',
	'pagedetail_trend_table_line_MinSubscriber': 'Min Subscribers',	
	'pagedetail_trend_table_line_AvgSubscriber': 'Avg Subscribers',
	'pagedetail_trend_table_line_MaxComment': 'Max Comments',
	'pagedetail_trend_table_line_MinComment': 'Min Comments',	
	'pagedetail_trend_table_line_AvgComment': 'Avg Comments',
	'pagedetail_chart_title_VideoNumWatchNum':"Total Videos and Video Views",
	'tip_Ytb_VideoNumWatchNum':"The total number of page's videos and number of video views.",
	'tooltip_Ytb_VideoNumWatchNum':"The total number of page's videos and number of video views, during the selected time range.",
	'pagedetail_trend_table_line_MaxYtbVideoNum': 'Max Videos',
	'pagedetail_trend_table_line_MinYtbVideoNum': 'Min Videos',	
	'pagedetail_trend_table_line_AvgYtbVideoNum': 'Avg Videos',
	'pagedetail_trend_table_line_MaxYtbWatchNum': 'Max Video Views',
	'pagedetail_trend_table_line_MinYtbWatchNum': 'Min Video Views',	
	'pagedetail_trend_table_line_AvgYtbWatchNum': 'Avg Video Views',
	'pagedetail_chart_title_addVideoNum':"Growth of Videos",
	'tooltip_Ytb_addVideoNum':"The number of growth of videos.",
	'pagedetail_chart_title_dayaddWatchNum':"Growth of Views",
	'pagedetail_chart_title_addWatchNum':"Growth of Video Views",
	'tooltip_Ytb_addWatchNum':"The number of growth of video views, during the selected time range.",
	'pagedetail_chart_title_addCommentNum':"Growth of Video Length",
	'pagedetail_chart_title_addCommentNum1':"Growth of Video Length(s)",
	'tooltip_Ytb_addCommentNum':"The number of growth of comments, during the selected time range.",
	'pagedetail_trend_table_line_SumYtbaddVideoNum': 'Total Growth of Videos',
	'pagedetail_trend_table_line_MaxYtbaddVideoNum': 'Max Growth of Videos',
	'pagedetail_trend_table_line_MinYtbaddVideoNum': 'Min Growth of Videos',	
	'pagedetail_trend_table_line_AvgYtbaddVideoNum': 'Avg Growth of Videos',
	'pagedetail_trend_table_line_SumYtbaddWatchNum': 'Total Growth of Views',
	'pagedetail_trend_table_line_MaxYtbaddWatchNum': 'Max Growth of Views',
	'pagedetail_trend_table_line_MinYtbaddWatchNum': 'Min Growth of Views',	
	'pagedetail_trend_table_line_AvgYtbaddWatchNum': 'Avg Growth of Views',
	'pagedetail_trend_table_line_SumYtbaddCommentNum': 'Total Growth of Video Length(s)',
	'pagedetail_trend_table_line_MaxYtbaddCommentNum': 'Max Growth of Video Length(s)',
	'pagedetail_trend_table_line_MinYtbaddCommentNum': 'Min Growth of Video Length(s)',	
	'pagedetail_trend_table_line_AvgYtbaddCommentNum': 'Avg Growth of Video Length(s)',
	// YouTube-主页详情-视频
	'pagedetail_trend_table_line_VideoNum': 'Number of Video',
	'pagedetail_trend_table_line_CurrentPublishVideoNum':'Current Videos',
	'pagedetail_trend_table_line_MaxPublishVideoNum':'Max Videos',
	'pagedetail_trend_table_line_MinPublishVideoNum':'Min Videos',
	'pagedetail_trend_table_line_GrowthVideoAndEngagement': 'Videos and Engagements',
	'pagedetail_growth_of_video': 'Growth of Videos',
	'pagedetail_trend_table_line_TotalVideos': 'Total Growth of Videos',
	'pagedetail_trend_table_line_MaxPerDayPublishVideo': 'Max Growth of Videos',
	'pagedetail_trend_table_line_MinPerDayPublishVideo': 'Min Growth of Videos',	
	'pagedetail_trend_table_line_AvgPerDayPublishVideo': 'Avg Growth of Videos',
	'pagedetail_trend_table_line_TotalEngagement': 'Total Engagements',
	'pagedetail_trend_table_line_MaxPerDayEngagement': 'Max Engagements',
	'pagedetail_trend_table_line_MinPerDayEngagement': 'Min Engagements',	
	'pagedetail_trend_table_line_AvgPerDayEngagement': 'Avg Engagements',
	'pagedetail_duration': 'Video Length',
	'pagedetail_one': '',
	// YouTube-主页详情-视频-悬浮框
	'tooltip_homepage_post_video_num': 'The total number of page\'s videos, during the selected time range',
	'tooltip_growth_video_and_engagement': 'The correlation between number of posts and engagements',
	// YouTube-主页详情-视频-右侧tip
	'tip_homepage_post_video_num': 'The total number of page\'s videos',
	'tip_growth_video_and_engagement': 'The correlation between number of posts and engagements',
	// YouTube分析-主页详情-订阅者
	'pagedetail_subscriber':'Subscribers',
	'pagedetail_total_subscriber': 'Total Subscribers',
	'pagedetail_chart_title_subscriberGrowth':'Number of Growth of Subscribers',
	'pagedetail_chart_title_subscriberGrowthAndVideoEngagement':'Growth of Subscribers and engagements',
	'tooltip_subscriber':"The total number of Page's subscribers, during the selected time range.",
	'tooltip_subscriber_growth':"The number of growth of subscribers, during the selected time range.",
	'tooltip_subscriber_growth_and_video_engagement':"The relevance between growth of subscribers and engagements.",
	'tip_subscriber':"The total number of Page's subscribers.",
	'tip_subscriber_growth':"The number of growth of subscribers.",
	'tip_subscriber_growth_and_video_engagement':"The relevance between growth of subscribers and engagements.",
	'pagedetail_trend_table_line_CurrentsubscriberNum':' Current Subscribers',
	'pagedetail_trend_table_line_MaxPerDaysubscriberNum':'Max Subscribers',
	'pagedetail_trend_table_line_MinPerDaysubscriberNum':' Min Subscribers',
	'pagedetail_trend_table_line_TotalsubscriberNum':' Total Growth of Subscribers',
	'pagedetail_trend_table_line_MaxPerDaysubscriberGrowthNum':' Max Growth of Subscribers',
	'pagedetail_trend_table_line_MinPerDaysubscriberGrowthNum':' Min Growth of Subscribers',
	'pagedetail_trend_table_line_AvgPerDaysubscriberGrowthNum':'Avg Growth of Subscribers',
	'pagedetail_trend_table_line_MaxsubscriberChange':' Max Growth of Subscribers',
	'pagedetail_trend_table_line_MaxsubscriberChangeCurrentDayEngagement':'Total Engagemetns on Max Growth Day',	
	// YouTube分析-主页详情-互动
	'pagedetail_chart_title_WatchNum':"Total Video Views",
	'pagedetail_chart_title_ViewNum':"Total Video Views",
	'pagedetail_chart_title_addWatchNum':"Number of Growth of Video Views",
	'pagedetail_chart_title_videoEvaluate':"Videos' Likes and Dislikes",
	'pagedetail_chart_title_videoEngagement':"Number of Engagements by Type",
	'pagedetail_chart_title_ThsEngagementByType':"Number of Engagements per 1k Subscribers",
	'pagedetail_chart_title_SingleVideoEngagement':"Average Engagements per Video",
	'pagedetail_chart_title_EngagementScale':"Proportion of Engagements",
	'tooltip_Ytbvideo_WatchNum':"The total number of video views, during the selected time range.",
	'tooltip_Ytbvideo_addWatchNum':"The number of growth of video views, during the selected time range.",
	'tooltip_Ytbvideo_videoEvaluate':"The number of videos' likes and dislikes, during the selected time range.",
	'tooltip_Ytbvideo_videoEngagement':"The number of Engagements (Likes + Dislikes + Comments),during the selected time range.",
	'tooltip_Ytbvideo_ThsEngagementByType':"The average number of engagements per 1,000 fans (= the sum of engagements / the number of total fans * 1000),during the selected time range.",
	'tooltip_Ytbvideo_SingleVideoEngagement':"The average number of engagements per post (= the sum of engagements / the sum of videos), during the selected time range.",
	'tooltip_Ytbvideo_EngagementScale':"The proportion of each type of engagements (Likes, Dislikes, Comments), during the selected time range.",
	'tip_Ytbvideo_WatchNum':"The total number of video views.",
	'tip_Ytbvideo_addWatchNum':"The number of growth of video views.",
	'tip_Ytbvideo_videoEvaluate':"The number of videos' likes and dislikes.",
	'tip_Ytbvideo_videoEngagement':"The number of Engagements (Likes + Dislikes + Comments).",
	'tip_Ytbvideo_ThsEngagementByType':"The average number of engagements per 1,000 fans (= the sum of engagements / the number of total fans * 1000).",
	'tip_Ytbvideo_SingleVideoEngagement':"The average number of engagements per post (= the sum of engagements / the sum of videos).",
	'tip_Ytbvideo_EngagementScale':"The proportion of each type of engagements (Likes, Dislikes, Comments).",
	'pagedetail_trend_table_line_CurWatchNum':'Current Video Views',
	'pagedetail_trend_table_line_MaxWatchNum':'Max Video Views',
	'pagedetail_trend_table_line_MinWatchNum':'Min Video Views',
	'pagedetail_trend_table_line_SumVideoWatchNum':'Total Growth of Video Views',
	'pagedetail_trend_table_line_MaxVideoWatchNum':'Max Growth of Video Views',
	'pagedetail_trend_table_line_MinVideoWatchNum':'Min Growth of Video Views',
	'pagedetail_trend_table_line_AvgVideoWatchNum':'Avg Growth of Video Views',
	'pagedetail_trend_table_line_SumVideoGetTop':'Total Likes',
	'pagedetail_trend_table_line_MaxVideoGetTop':'Max Likes',
	'pagedetail_trend_table_line_MinVideoGetTop':'Min Likes',
	'pagedetail_trend_table_line_AvgVideoGetTop':'Avg Likes',	
	'pagedetail_trend_table_line_SumVideoGetTread':'Total Dislikes',
	'pagedetail_trend_table_line_MaxVideoGetTread':'Max Dislikes',
	'pagedetail_trend_table_line_MinVideoGetTread':'Min Dislikes',
	'pagedetail_trend_table_line_AvgVideoGetTread':'Avg Dislikes',
	'pagedetail_trend_table_line_SumVideoEngagement':'Sum Engagements',
	'pagedetail_trend_table_line_MaxVideoEngagement':'Max Engagements',
	'pagedetail_trend_table_line_MinVideoEngagement':'Min Engagements',
	'pagedetail_trend_table_line_AvgVideoEngagement':'Avg Engagements',	
	'pagedetail_trend_table_line_SumThsVideoEngagement':' Sum Engagement per 1k Subscribers',
	'pagedetail_trend_table_line_MaxThsVideoEngagement':'Max Engagement per 1k Subscribers',
	'pagedetail_trend_table_line_MinThsVideoEngagement':'Min Engagement per 1k Subscribers',
	'pagedetail_trend_table_line_AvgThsVideoEngagement':'Avg Engagement per 1k Subscribers',	
	'pagedetail_trend_table_line_CurSingleVideoEngagement':'Average No. of Engagements per Video of the Period',
	'pagedetail_trend_table_line_MaxSingleVideoEngagement':'Max Average No. of Engagements per Video of the Period',
	'pagedetail_trend_table_line_MinSingleVideoEngagement':'Min Average No. of Engagements per Video of the Period',
	'pagedetail_trend_table_line_AvgSingleVideoEngagement':'Avg Average No. of Engagements per Video of the Period',
	// 分析-悬浮框信息
	'tooltip_likes':'Likes',
	'tooltip_post_likes':'Reactions',
	'tooltip_post_shares':'Shares',
	'tooltip_post_comments':'Comments',
	'tooltip_shares':'Share',
	'tooltip_post':'Posts',
	'tooltip_all':'All',
	'tooltip_comments':'Comments',
	'tooltip_photo':'Photo',
	'tooltip_video':'Video',
	'tooltip_active':'Engagement',
	'tooltip_link':'Link',
	'tooltip_status':'Text',
	'tooltip_other':'Other',
	'tooltip_value':'All',
	'tooltip_like': 'Likes',
	'tooltip_love': 'Love',
	'tooltip_wow': 'Wow',
	'tooltip_haha': 'Haha',
	'tooltip_sad': 'Sad',
	'tooltip_angry': 'Angry',
	'facebook_tooltip_all':'All',
	'facebook_tooltip_likes':'Reactions',
	'facebook_tooltip_shares':'Shares',
	'facebook_tooltip_comments':'Comments',
	'facebook_tooltip_active':'Engagement',
	'twitter_tooltip_likes':'Likes',
	'twitter_tooltip_shares':'Retweets',
	'twitter_tooltip_all':'All',
	'twitter_tooltip_comments':'Replies',
	'instagram_tooltip_all':'All',
	'instagram_tooltip_likes':'Likes',
	'instagram_tooltip_comments':'Comments',
	'youtube_tooltip_likes':'Likes',
	'youtube_tooltip_dislikes':'DisLikes',
	'youtube_tooltip_comments':'Comments',
	'tooltip_hide_all_clicks':'Hide All Clicks',
    'tooltip_hide_clicks':'Hide Clicks',
    'tooltip_comment':'Comments',
    'tooltip_page_negative_feedback_by_type':'Hide',
    'tooltip_report_spam_clicks':'Report Spam Clicks',
    'tooltip_unlike_page_clicks':'Unlike Page Clicks',
    'tooltip_xbutton_clicks':'Xbutton Clicks',
    'tooltip_answer':'Answer',
    'tooltip_claim':'Claim',
    "tooltip_page_positive_feedback_by_type":'Positive Feedback',
    "tooltip_other clicks":'Others',
    "tooltip_photo view":"Photos",
    "tooltip_video play":'Videos',
    "tooltip_link clicks":'Links',
    "tooltip_button clicks":'Buttons',
    "tooltip_page_fans_by_unlike_source_unique":"",
    "tooltip_Ads":'Ads',
    "tooltip_News Feed":'Your Page',
    "tooltip_Your Page":'News Feed',
    "tooltip_Page Suggestions":'Page Suggestions',
    "Restored Likes from Reactivated Accounts":"Restored Likes from Reactivated Accounts",
    "tooltip_Search":"Search",
    "tooltip_Restored Likes from Reactivated Accounts":'Restored Likes from Reactivated Accounts',
    "tooltip_Deactivated or Memorialized Account Removals":'Deactivated or Memorialized Account Removals',
    "tooltip_Unlikes from Page, Posts, or News Feed":'Unlikes From Page, Posts, or News Feed',
	"tooltip_Unlikes from Page Suggestions":'Unlikes from Page Suggestions',
    "tooltip_Other":'Other',
    "tooltip_Suspicious Account Removals":'Suspicious Account Removals',
    "tooltip_Unlikes from Search":'Unlikes from Search',
    "tooltip_page_impressions_organic":'Organic Page Impressions',
    "tooltip_page_impressions_paid":'Paid Page Impressions',
    "tooltip_page_posts_impressions_organic":'Organic Post Impressions',
    "tooltip_page_posts_impressions_paid":'Paid Page Impressions',
	"tooltip_page_video_views_10s_autoplayed":'10s Video Autoplayed',
	"tooltip_page_video_views_10s_click_to_play":'10s Video Click to Paly',
	"tooltip_page_video_complete_views_30s_autoplayed":'30s Video Autoplayed',
	"tooltip_page_video_complete_views_30s_click_to_play":'30s Video Click to Play',
	"tooltip_funnle_all":'All',
	"tooltip_funnle_10s":'10s',
	"tooltip_funnle_30s":'30s',
	"tooltip_os_Rating":'Current OS Rating',
	//漏斗图
	'FunnleChart_SelectType_all':'All',
	'FunnleChart_SelectType_organic':'Organic',
	'FunnleChart_SelectType_paid':'Paid',
	// 灵感-导航
	'inspiration_title_Pagetypes':'Post Type',
	'inspiration_title_Choose a specific homepage':'Select Page',
	'inspiration_facebook_inspiration': 'Facebook Inspiration',
	'inspiration_twitter_inspiration': 'Twitter Inspiration',
	'inspiration_instagram_inspiration': 'Instagram Inspiration',
	'inspiration_youtube_inspiration': 'YouTube Inspiration',
	'inspiration_linkedin_inspiration': 'LinkedIn Inspiration',
	'inspiration_square': 'Inspiration Square',
	'inspiration_recentposts': 'Recent Posts',
	'inspiration_popularposts': 'Hottest Posts',
	'inspiration_hottestposts':'Hottest Posts',
	'inspiration_prefersharingposts': 'Highly-Shared Posts',
	'inspiration_positiveposts': 'Extremely-Fun Posts',
	'inspiration_negativeposts': 'Negative Posts',
	'inspiration_recentvideos':'Recent Videos',
	'inspiration_hottestvideos':'Hottest Posts',
	'inspiration_mostviewsvideos':'Most Video Views',
	'inspiration_Recent Posts Introduction':'New feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page selector and post type filter. The display order is arranged by posting time from recent to past, in order to deliver you the most recent happenings on social media.',
	'inspiration_Hottest Posts Introduction':'Inspiration Square “Hottest Posts” new feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page selector and post type filter. The display order is arranged by number of engagements of one post from most to least, in order to deliver you the hottest happenings on social media.',
	'inspiration_Highly-Shared Posts Introduction':'Inspiration Square “Highly-Shared Posts” new feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page selector and post type filter. The display order is arranged by “share” tendency of one post from most to least, in order to deliver you the most viral happenings on social media. Share tendency is calculated as the ratio of number of shares out of total number of engagements of one post. According to OneSight analytics, posts of share tendency more than 3% are posts of viral value.',
	'inspiration_Extremely-Fun Posts Introduction':'Inspiration Square “Extremely-Fun Posts” new feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page selector and post type filter. The display order is arranged by “LOL” tendency of one post from most to least, in order to deliver you the most amusing posts on social media. LOL tendency is calculated as the ratio of number of LOL out of total number of likes of one post. According to OneSight analytics, posts of LOL tendency more than 1% are posts of amusing value.',
	'inspiration_Negative Posts Introduction':'Inspiration Square “Negative Posts” new feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page selector and post type filter. The display order is arranged by “Anger” tendency of one post from most to least, in order to deliver you the most alerting posts on social media. Anger tendency is calculated as the ratio of number of Angers out of total number of likes of one post. According to OneSight analytics, posts of Anger tendency more than 1% are posts of alerting value.',
	'inspiration_Recent video Introduction':'Video feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page tag selector. The display order is arranged by posting time from recent to past, in order to deliver you the most recent happenings on social media.',
	'inspiration_Hottest video Introduction':'Inspiration Square “Hottest Posts” video feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page tag. The display order is arranged by number of engagements of one post from most to least, in order to deliver you the hottest happenings on social media.',
	'inspiration_Most Views video Introduction':'Inspiration Square “Most Video Views” video feed shows the original content of the page you are following in the selected time period (Default as latest 28 days), supporting page tag. The display order is arranged by number of views’ times of one post from most to least, in order to deliver you the hottest happenings on social media.',
	'inspiration_seekinspiration': 'Find Inspiration',
	'inspiration_SelectPageType_photo':"Photos",
	'inspiration_SelectPageType_video':"Videos",
	'inspiration_SelectPageType_status':"Texts",
	'inspiration_SelectPageType_link':"Links",
	'inspiration_SelectPageType_IMAGE':"Photos",
	'inspiration_SelectPageType_VIDEO':"Videos",
	'inspiration_SelectPageType_carousel_album':"Carousels",
	'inspiration_SelectPageType_CAROUSEL_ALBUM':"CAROUSEL ALBUM",
	// 'inspiration_postmain_facebook_post_engagement':'Engagement',
	'inspiration_SelectPageType_youtube_post_created_time':"Recent Videos",
	'inspiration_SelectPageType_youtube_post_engagements':"Hottest Videos",
	'inspiration_SelectPageType_youtube_view_count':"Most Views Videos",
	'inspiration_SelectPageType_linkedin_post_created_time':"Recent Posts",
	'inspiration_SelectPageType_linkedin_post_engagements':"Hottest Posts",
	'inspiration_postmain_facebook_post_engagements':'Interactions',
	'inspiration_postmain_facebook_post_likes':'Reactions',
	'inspiration_postmain_facebook_post_like_haha':'Haha',
	'inspiration_postmain_facebook_post_like_angry':'Angry',
	'inspiration_postmain_facebook_post_shares':'Shares',
	'inspiration_postmain_facebook_post_comments':'Comments',
	'inspiration_postmain_facebook_prefersharing':'Sharing Prefer',
	'inspiration_postmain_facebook_Anger tendency':'Negative Prefer',
	'inspiration_postmain_facebook_LaughingTendency':'Positive Prefer',
	'inspiration_postmain_twitter_post_engagements':'Engagement',
	'inspiration_postmain_twitter_post_likes':'Likes',
	'inspiration_postmain_twitter_post_shares':'Retweets',
	'inspiration_postmain_twitter_post_comments':'Replies',
	'inspiration_postmain_instagram_post_engagements':'Engagement',
	'inspiration_postmain_instagram_post_likes':'Likes',
	'inspiration_postmain_instagram_post_comments':'Comments',
	'inspiration_postmain_collected':'Favorited',
	'inspiration_postmain_Collection_post':'Favorite',
	'inspiration_postmain_Collection_Video':'Favorite',
	'inspiration_postmain_youtube_view_count':"Video Views",
	'inspiration_postmain_youtube_post_likes':"Likes",
	'inspiration_postmain_youtube_post_dislikes':"Dislikes",
	'inspiration_postmain_youtube_post_comments':"Comments",
	'inspiration_postmain_linkedin_post_engagements':"互动",
	'inspiration_postmain_linkedin_post_likes':"点赞",
	'inspiration_postmain_linkedin_post_comments':"评论",
	// 全球榜单-导航
	'globallist_facebook_list': 'Facebook List',
	'globallist_brand_list': 'Brand List',
	'globallist_brand_total_list': 'General Brand List',
	'globallist_industry_brand_list': 'Industry Brand List',
	'globallist_post_list': 'Post List',
	'globallist_twitter_list': 'Twitter List',
	'globallist_instagram_list': 'Instagram List',
	'globallist_Top_20_China_Brand': 'Top 20 China Brand',
	'globallist_China_Brand_Top_20': 'Top 20 China Brand',
	'globallist_global_list': 'Global List',
	// 全球榜单-中国出海20强
	'globallist_score': 'Score',
	// 全球榜单-品牌榜
	'globallist_facebook_brand_list': 'Facebook Brand List',
	'globallist_twitter_brand_list': 'Twitter Brand List',
	'globallist_instagram_brand_list': 'Instagram Brand List',
	'globallist_daily_list': 'Daily list',
	'globallist_week_list': 'Week list',
	'globallist_month_list': 'Month list',
	'globallist_all_industry': 'All industries',
	'globallist_facebook_industry_brand_list': 'Facebook Industry brand list',
	'globallist_twitter_industry_brand_list': 'Twitter Industry brand list',
	'globallist_brand': 'Brand',
	'globallist_contain_page_num': 'Number of page',
	'globallist_belong_to_industry': 'Industry',
	'globallist_fan': 'Fan',
	'globallist_brand_score': 'OS Rating',
	'globallist_onesight_say': 'Brand Declaration',
	'globallist_onesight_say_text': 'Success is not by accident',
	'globallist_spread_more': 'Show more',
	'globallist_scoring_mode': 'OS Rating Methodology',
	// 全球榜单-评分详情
	'globallist_fans_score': 'Fans Rating',
	'globallist_fans_diff_score': 'Growth of Fans Rating',
	'globallist_post_score': 'Posts Rating',
	'globallist_post_engagement_score': 'Engagements Rating',
	'globallist_thousand_people_engagement_score': 'Engagements per 1k Fans Rating',
	// 全球榜单-行业选择器
	'globallist_back': 'back ',
	'globallist_all': 'all ',
	'globallist_industry': 'industry',
	'globallist_please_choose_industry': 'Please select the industry',
	// 全球榜单-主页列表
	'globallist_homepage': 'Page',
	'globallist_country': 'Country',
	'globallist_homepage_link': 'Link',
	'globallist_homepage_score': 'Score',
	'globallist_attention': 'Attention',
	// 全球榜单-提名入榜
	'globallist_nominate': 'Nominate',
	'globallist_enter_your_homepage_information': 'Please enter the homepage information you want to add.',
	'globallist_page_link': 'Page Link',
	'globallist_market_oriented': 'Market oriented',
	'globallist_subordinate_brand': 'Brand',
	'globallist_brand_country': 'Brand Country',
	'globallist_chinese_brand': 'Chinese Brand' ,
	'globallist_subordinate_industry': 'Industry',
	'globallist_nominate_reason': 'Reason',
	'globallist_nominate_confirm': 'OK',
	'globallist_nominate_search': 'Search',
	'globallist_nominate_submit': 'Submit',
	'globallist_nominate_cancel': 'Cancel',
	'globallist_nominate_edit': 'Edit',
	'globallist_input_page_link_tip': 'Please input the page link!',
	'globallist_confirm_page_link_tip': 'Please confirm the page link！',
	'globallist_input_country': 'Please choose a country',
	'globallist_input_country_tip': 'Please choose a country!',
	'globallist_input_brand_name': 'Please input the brand name',
	'globallist_input_brand_name_tip': 'Please input the brand name!',
	'globallist_choose_industry': 'Please choose a industry',
	'globallist_choose_industry_tip': 'Please choose a industry!',
	'globallist_submit_success': 'Successfully! Thank you for your suggestion!',
	'globallist_continue_follow_list': 'Please continue to follow the list!',
	// 全球榜单-帖文榜
	'globallist_facebook_postlist': 'Facebook Post List',
	'globallist_twitter_postlist': 'Twitter Post List',
	'globallist_instagram_postlist': 'Instagram Post List',
	'globallist_post_language': 'Post language: ',
	'globallist_english': 'English',
	'globallist_chinese': 'Chinese',
	'globallist_post_interaction': 'Post Engagements ',
	'globallist_interaction': 'Engagements',
	'globallist_post_performance': 'Post performance',
	'globallist_positive_mood': 'Positive',
	'globallist_sharing': 'Shares',
	'globallist_haha': 'Haha',
	'globallist_angry': 'Angry',
	'globallist_proportion_of_interaction': 'proportion',
	'globallist_exceed': 'More than',
	'globallist_post': 'Posts',
	'globallist_post_has_no_text': 'This post has no text',
	'globallist_share_is_the_best': 'Share is the best!',
	'globallist_can_you_be_funnier': 'Can you be funnier?',
	'globallist_good_words_worth_a_million': 'Good words worth a million!',
	'globallist_negative_event_deal_with_it': 'Negative events！Deal with it!',
	'globallist_top_100_posts': 'Top 100 posts!',
	// 公共汉化
	'onesight': 'OneSight',
	'aboutus': 'About us',
	'addpage':'Add Pages',
	'disclaimer':'disclaimer',
	'search':'Search',
	'global': 'Global',
	'common_to':'to',
	'common_day':'days',
	'common_hour':'hours',
	'common_fans':'Fans',
	'common_select_list_placeholder':'Input Keyword',
	'common_search':'Search',
	'common_single':'个',
	'common_analysis_title_tip':'Click Page to enter Page Details get more page data.',
	'common_usercolor_nofill':'No Fill',
	'common_deltile':'Are you sure you want to delete?',
	'common_deltile_btn_sure':'Delete',
	'common_deltile_btn_sures':'Confirm',
	'common_deltile_btn_Add':'Add',
	'common_deltile_btn_cancel':'Cancel',
	'common_deltile_btn_cancels':'Cancel',
	'common_emptylist_title_left':'Now, add an ',
	'common_emptylist_title_right':' page!',
	'common_search_null':"Can't find the specified Page.",
	'common_post_noData':'No Posts',
	'common_noData':'No Data',
	'YoutubeVideo_common_noData':'There is no new videos posted in currently selected period.',
	'YoutubeLike_common_noData':'There is no new videos posted in currently selected period.',
	'YoutubeVideoEngagement_common_noData':'There is no new videos posted in currently selected period.',
	'common_changeauthData':'Switch to Insights Data',
	'common_changepubData':'Switch to Public Data',
	'common_View_Details':'View',
	'common_Load_More': 'Load more',
	'common_Return_platform': 'Return platform',
	//时间控件
	'OSDateRangePicker_yesterday':'Yesterday',
	'OSDateRangePicker_last_7_days':'Last 7 Days',
	'OSDateRangePicker_last_28_days':'Last 28 Days',
	'OSDateRangePicker_last_90_days':'Last 90 Days',
	'OSDateRangePicker_last_week':'Last Week',
	'OSDateRangePicker_last_month':'Last Month',
	'OSDateRangePicker_selected':'Selected',
	'OSDateRangePicker_Mon':'Mon',
	'OSDateRangePicker_Tues':'Tues',
	'OSDateRangePicker_Wed':'Wed',
	'OSDateRangePicker_Thur':'Thur',
	'OSDateRangePicker_Fri':'Fri',
	'OSDateRangePicker_Sat':'Sat',
	'OSDateRangePicker_Sun':'Sun',
	// 我的素材库
	'MyFavorite_Favorite_post':'Favorite post',
	'MyFavorite_NO_Favorite':"You haven't bookmarked any posts yet, you can bookmark them on the post list and post details page.",
	'MyFavorite_Recent':'Recent',
	'MyFavorite_Seven':'Previous 7 days',
	'MyFavorite_TwentyEight':'Previous 28 days',
	'MyFavorite_All':'All',
	'MyFavorite_link':'link',
	'MyFavorite_photo':'photo',
	'MyFavorite_VIDEO':'video',
	'MyFavorite_video':'video',
	'MyFavorite_status':'status',
	'MyFavorite_IMAGE': 'photo',
	'MyFavorite_CAROUSEL_ALBUM': 'rotation chart',
	'MyFavorite_event':'',
	'MyFavorite_Favorited':'Favorited',
	//帖文详情弹框
	'postDetailPopup_basedata':'Basic Data',
	'postDetailPopup_basedata_mood':'Reactions',
	'postDetailPopup_basedata_engagement':'Engagement',
	'postDetailPopup_basedata_share':'Shares',
	'postDetailPopup_basedata_comments':'Comments',
	'postDetailPopup_emotionAnal':'Sentiment Analysis',
	'postDetailPopup_emotionAnal_positive':'Positive',
	'postDetailPopup_emotionAnal_passive':'Negative',
	'postDetailPopup_authdata':'Insights Data',
	'postDetailPopup_authdata_impressions':'Post Impressions',
	'postDetailPopup_authdata_impressions_organic':'Organic',
	'postDetailPopup_authdata_impressions_paid':'Paid',
	'postDetailPopup_authdata_impressions_fan':'To Fans',
	'postDetailPopup_authdata_impressions_unfan':'To Non-Fans',
	'postDetailPopup_authdata_clicks':'Post Clicks',
	'postDetailPopup_authdata_clicks_photo':'Photos ',
	'postDetailPopup_authdata_clicks_video':'Videos',
	'postDetailPopup_authdata_clicks_link':'Links',
	'postDetailPopup_authdata_clicks_other':'Others',
	'postDetailPopup_authdata_negative_feedback':'Negative Feedback',
	'postDetailPopup_authdata_negative_feedback_hide':'Hide',
	'postDetailPopup_authdata_negative_feedback_hideall':'Hide All',
	'postDetailPopup_authdata_negative_feedback_unlike':'Unlike Page',
	'postDetailPopup_authdata_negative_feedback_report':'Report Spam',
	'postDetailPopup_applyfor':'You could apply “Download Video” for this video, after success, OS will download this video for you and add to your library. The price of this request will up to your traffic. More details go to “',
	'postDetailPopup_applyfor_open':'Growth Tools',
	'postDetailPopup_lifetime':'You could apply “Realtime engagement” for this post,  after success, OS will obtain the Engagement of this post every hour and draw a next 7 - day Engagement trend graph for you.',
	'postDetailPopup_lifetime_open':'Ask for Realtime engagement',
	'postDetailPopup_lifetime_period':'Realtime Engagement',
	'postDetailPopup_post_goopen':'View on ',
	'postDetailPopup_post_open':' ',
	'postDetailPopup_video_open':' ',
	'postDetailPopup_previous': 'Previous',
	'postDetailPopup_next': 'Next',
	// 常见问题解答
	'common_problem':'FAQ',
	'common_problem_contact_we':'Contact Us',
	'common_problem_contact_faq':'商家主页转换',
	'common_problem_explain':'FAQ is here, for your questions.',
	//twitter 主页详情
	//twitter 粉丝
	"twitter_pagedetail_chart_title_Fans":'Total Fans',
	'twitter_pagedetail_trend_table_line_CurrentFansNum':'Current Fans',
	'twitter_pagedetail_trend_table_line_MaxPerDayFansNum':'Max Fans',
	'twitter_pagedetail_trend_table_line_MinPerDayFansNum':'Min Fans',
	"twitter_pagedetail_chart_title_FansGrowth":'Number of Growth of Fans',
	'twitter_pagedetail_trend_table_line_TotalFansNum':'Total Change of Fans',
	'twitter_pagedetail_trend_table_line_MaxPerDayFansGrowthNum':'Max Change of Fans',
	'twitter_pagedetail_trend_table_line_MinPerDayFansGrowthNum':'Min Change of Fans',
	'twitter_pagedetail_trend_table_line_AvgPerDayFansGrowthNum':'Avg Change of Fans',
	'twitter_pagedetail_chart_title_FansGrowthAndPostEngagement':"Growth of Fans and Engagements",
	'twitter_pagedetail_trend_table_line_MaxFansChange':'Max Change of Fans',
	'twitter_pagedetail_trend_table_line_MaxFansChangeCurrentDayEngagement':'Total Engagement on Max Change Day',
	"twitter_pagedetail_chart_title_interactive":'Top 50 Interacted Fans',
	"twitter_pagedeilte_Top 50 Interacted Fans_cont":'The top 50 followers who interacted with the page.',
	'twitter_fanspagetableTitle_rank':'Rank',
	'twitter_fanspagetableTitle_user':'User',
	'twitter_fanspagetableTitle_Interact_with_me':'Interacted with Me',
	'twitter_fanspagetableTitle_shares_me':'Interact with Me',
	'twitter_fanspagetableTitle_comments_me':'Comments Me',
	'twitter_fanspagetableTitle_@_me':'@ Me',
	'twitter_fanspagetableTitle_fansTa':'His Fans',
	"tooltip_text":'Text',
	"pagedetail_chart_title_":"Proportion of Engagement of Posts by Posts's Type",
	"pagedetail_chart_title_postType":'Posts by Type',
	"pagedetail_chart_title_postNum":'Number of Posts',
	"pagedetail_chart_title_postEngagement":'Total Engagements',
	"pagedetail_chart_title_postEngagementRatio":'Shares',
	// 增长工具
	'IncreaseTool_All':'Growth Tool',
	'IncreaseTool_DowloadHistory':'Report Management',
	'IncreaseTool_EmotionAnalysis':'Comments Senti',
	'IncreaseTool_EmotionAnalysis_Info':"There are many scenarios for social media management. While managing an e-commerce brand page, sellers need to be always concerned about whether users' comments are positive. For example, to launch a new product for overseas market, extensive and continuous watch of market input is crucial.Popular posts on social media can all produce thousands of text reviews, #CommentSenti make use of natural language programing ability, capable of watching fans sentiment starting from a single post.",
	'IncreaseTool_DownloadPDF':'Download Report',
	'IncreaseTool_Publisher':'Publisher',
	'IncreaseTool_DownliadHist':'导出报告管理',
	'IncreaseTool_DownloadPDF_Info':'A timely and consistent reporting system is critical to social media management. For a global brand manager, organizing weekly reporting system from global market is a huge operational challenge. Onesight’s generates report for you, with our in-product data and information structure.  Export function support CSV and PDF formats, 7 types of key data dimensions choice, and support product customization. And there is no authorization necessarily required. Popular templates include:',
	'IncreaseTool_DownloadPDF_somelTitle_one':'Brand Page Operation Report (a standard data report)',
	'IncreaseTool_DownloadPDF_somelTitle_two':'Brand Page Post Report (a data + content report)',
	'IncreaseTool_DownloadPDF_somelTitle_three':'Industry multi-brand report (a multi-brand data integration report)',
	'IncreaseTool_TagCount':'Tags Counter',
	'IncreaseTool_Data_Tip':'Thanks for your waiting. We’ll contact you soon within 24 hours and will be put off if it is holiday.',
	'IncreaseTool_In_audit':'In audit',
	'IncreaseTool_Use_Application':'Use application',
	'IncreaseTool_look_examplePDF':'View Sample',
	'IncreaseTool_EmotionAnalysis_BottomInfo':'Sentiment analysis has lots of use cases, such as an e-commerce page, sellers need to keep notice of the product review. Then the promotion planning of a new product come into the oversea market, here is very important for this product to devote into social media. Each hot post can bring thousands of words comments, #CommentSenti use sentiment analysis to analyze the public voice.',
	'IncreaseTool_DownloadPDF_BottomInfo':'OneSight auto-export report can make report by one-step, data resource and visualization is consistent as product, support PDF and csv. 7 types of data for your choice, OS also can meet your customized report needs. Currently, you can choose report include:',
	'IncreaseTool_DownloadPDF_BottomInfo_list_1':'Page Operation Report（Pure Number Data）',
	'IncreaseTool_DownloadPDF_BottomInfo_list_2':'Page Posts Report（Data + Content）',
	'IncreaseTool_DownloadPDF_BottomInfo_list_3':'Page Competitor Report（Multi-Brand Data Integration）',
	'IncreaseTool_Release_BottomInfo':'Publishing tools let you post posts on overseas social platforms.Authorize, publish and view data.One-stop service makes it easy to speak on overseas platforms. ',
	'IncreaseTool_Release_BottomInfo_list_1':'Set post time: Efficiently schedule your release schedule.',
	'IncreaseTool_Release_BottomInfo_list_2':'Post preview: Let you experience the original post status.',
	'IncreaseTool_Release_BottomInfo_list_3':'View post details: Lets you visualize the data in your post.',
	'IncreaseTool_Release_BottomInfo_list_4':'The overseas social platforms currently supported are Facebook and Twitter.',
	//twitter// 互动
	'pagedetail_trend_table_line_MaxEngagementPost':"Max Engagement Post Type",
	'pagedetail_trend_table_line_MinEngagementPost':"Min Engagement Post Type",
	//Dashboard 
	"Dashboard_postEngagement":'Engagement',
	"Dashboard_post":'Posts',
	"Dashboard_fansDiff":'Growth of Fans',
	"Dashboard_fans":'Total Fans',
	'Dashboard_postEnaggement_num':'Post Enaggements',
	"Dashboard_title_welcome":'Welcome to OneSight Global Marketing Cloud —— Global Brand Incubator.',
	"Dashboard_Data":'You Currently Use',
	"Dashboard_Following_pages":'Following Pages',
	"Dashboard_Following_posts":'Favorited Posts',
	"Dashboard_Paid_Services":'Paid Services',
	"Dashboard_DataOverview":'Dashboard Mode Page Data as Follow ',
	"Dashboard_TimeLook":'Current Page',
	'Dashboard_28TimeData':'Last 28 Days Data',
	"Dashboard_echarts_title":'Key Datas',
	"Dashboard_Description_fans":'   Total Fans is the best certification of Page.',
	"Dashboard_Description_fansDIff":'   You can get the increase or decrease in fans directly.',
	"Dashboard_Description_post":'   Posting is the basis of increasing fans.',
	"Dashboard_Description_post_engagement":'   Engagement help you directly understand your  audience.',
	"Dashboard_flover_page":'Analytics can manage your page.',
	"Dashboard_flover_Post":'Inspiration can find valuable posts.',
	"Dashboard_flover_Paid":'Tools can help your marketing.',
	"Dashboard_goNow":'Go Now',
	"Dashboard_Go to Page Details":'Go to Page Details',
	'Dashboard_yearsToday':'Key data performance yesterday',
	"Dashboard_err_NoAuth":'Connect with Facebook to get the Insights Data',
	"Dashboard_err_ThreePage":'You must choose 3 pages to export competitor report.',
	"Dashboard_err_SaveBtn":'Plese save your page setting.',
	"Dashboard_err_PageAuth":'You have not connected with facebook yet.',
	"Dashboard_err_Pay":'You have not paid yet.',
	"Dashboard_err_30PageNum":'PDF can export up to 30 posts in a single order',
	'Dashboard_err_Number':'Please enter the number',
	"Dashboard_SelectPage":'Select Page',
	"Dashboard_SavePage":'Save',
	"Dashboard_SaveSuccess":'Saved！',
	//change Info
	"ChangeInfo_title":'General Settings',
	"ChangeInfo_Name":'Name',
	"ChangeInfo_Company":'Company',
	"ChangeInfo_industry":'Industry',
	"ChangeInfo_Phone":'Phone',
	"ChangeInfo_Email":'Email',
	"ChangeInfoReport_an_error_Name":'Please enter your real name, so that we could provide better service.',
	"ChangeInfoReport_an_error_Company":'Please enter your company name, so that we could provide accurate service.',
	"ChangeInfoReport_an_error_industry":'Please select your/your company industry, so that we could provide customized service.',
	"ChangeInfo_Save":'Save',
	//授权
	"auth_Connect_Facebook_Insights":'Connect Facebook Insights',
	"auth_weNeedauthorization":'We need your authorization to get this page insights data',
	"auth_NotNow":'Not Now',
	"auth_Connect Facebook Insights":'Connect Facebook Insights',
	"auth_not Connect":'Cannot with Facebook',
	"auth_notFacebookauth":'Sorry, the Facebook account your loged in, dose not have this Page insights authorization',
	"auth_Try Later":'Try Later',
	'auth_need_connect':'If you are the owner of this page, you can use secured Facebook-login to review your page insights data, including extended data capabilities in customer profile, fans behavior, location and language preferences. (Remarks: Insight data is only readable by yourself, it will not be incorporated in public database.)',
	'auth_need_connect_now':'Connect Facebook Insights',
	'auth_need_connect_ok':'Connect insights Successfully',
	'auth_ok':'ok',
	// 申请演示表格
	"FormTable_Request_Demo_Form":"Request Demo Form",
	"FormTable_Applicant_Name":"Applicant Name",
	"FormTable_Company_Name":"Applicant’s Company Name",
	"FormTable_Department":"Applicant’s Department",
	"FormTable_Position":"Applicant’s Position",
	"FormTable_Tel_No":"Applicant’s Tel No.",
	"FormTable_Email_Address":"Applicant’s Email Address.",
	"FormTable_Industry":"Industry",
	"FormTable_Button":"Submit",
	// 申请演示表格错误信息
	"FormTable_err_real_name":"Please input your real name",
	"FormTable_err_company_name":"Please input your company name",
	"FormTable_err_department":"Please input department",
	"FormTable_err_position":"Please input position",
	"FormTable_err_accept_numbers":"Tel. No only accept numbers",
	"FormTable_err_Email_address":"Please input your Email address",
	"FormTable_err_industry":"Please select an industry",
	// 选择行业
	"FormTable_select_industry": "Select Industry",
	// 评论情感分析功能
	"ChargeTool_CommentSenti_Analytics":"CommentSenti Analytics",
	"ChargeTool_Function_left":"Function",
	"ChargeTool_Function_right":"Semantic Analysis",
	"ChargeTool_Platform_left":"Platform",
	"ChargeTool_Platform_right":"Facebook",
	"ChargeTool_Area_left":"Area",
	"ChargeTool_Area_right":"Facebook Post Comments",
	"ChargeTool_Language_left":"Language",
	"ChargeTool_Language_right":"English, Chinese and other 9 languages",
	"ChargeTool_Pricing_left":"Pricing",
	"ChargeTool_Pricing_right":"by usage",
	"ChargeTool_View_Sample":"View Sample",
	"ChargeTool_Request_Demo":"Request Demo",
	// 提交成功信息
	"ChargeIndex_success_top":"Your application has been submitted successfully. ",
	"ChargeIndex_success_bottom":"Our sales team will be in touch in 7 working days.",
	//添加页面facebook授权
	'Pleace_add_facebook_page':'Please select pages to OneSight Data Analytics:',
	'add_page':'Add',
	'add_page_list':'page to your OneSight Data Analytics',
	'add_page_lists':'pages to your OneSight Data Analytics',
	// 导出报告
	'ChargeDownloadPDF_Export_Report':'Export Report',
	'ChargeDownloadPDF_Functions':'Functions',
	'ChargeDownloadPDF_Free_Trial':'Free Trial',
	'ChargeDownloadPDF_SME_Solution_top':'SME Solution',
	'ChargeDownloadPDF_SME_Solution_bottom':' ',
	'ChargeDownloadPDF_Brand_Solution_top':'Brand Solution',
	'ChargeDownloadPDF_Brand_Solution_bottom':' ',
	'ChargeDownloadPDF_Request_Demo':'Request Demo',
	'ChargeDownloadPDF_Request_Go_Now':'Go Now',
	'ChargeDownloadPDF_Key_Metrics':'Key Metrics',
	'ChargeDownloadPDF_6':'6',
	'ChargeDownloadPDF_16':'16',
	'ChargeDownloadPDF_for_with_or_without_authorization':'for with or without authorization',
	'ChargeDownloadPDF_Monthly_Downloads':'Monthly Downloads',
	'ChargeDownloadPDF_3_Downloads':'3 Downloads',
	'ChargeDownloadPDF_Unlimited':'Unlimited',
	'ChargeDownloadPDF_No_of_Users':'No. of Users',
	'ChargeDownloadPDF_1_user':'1 user',
	'ChargeDownloadPDF_5_user':'5 user',
	'ChargeDownloadPDF_10_user':'10 user',
	'ChargeDownloadPDF_Export_PDF':'Export PDF',
	'ChargeDownloadPDF_Export_Excel':'Export Excel',
	'ChargeDownloadPDF_Export_Word':'Export Word',
	'ChargeDownloadPDF_6_Available_Templates':'6 Available Templates',
	'ChargeDownloadPDF_Customized_Templates':'Customized Templates',
	//新手指导
	'new_welcome':"Welcome to",
	'new_oneStop':"1-Stop Brand Social Media Analytics Platform",
	'new_step':'is a global social media markeing tools, helping monitor globalsocial media page. ',
	'new_use':'Please use this simple guide that we prepare for you !',
	'new_not':'Not Now',
	'new_Go':'GO Guide',
	'new_ok':'ok',
	'new_helping':'We are looking forward to helping you！',
	'new_wechat':'If you have any questions or suggestions, please feel free to contact us through Wechat.',
	'new_time':'Scan QR Code to add your 24 hours Wechat Customer Service.',
	'new_first_title':'Adding Pages on OneSight',
	'new_first_subtitle':'After successfully add pages， you will be able to view more page data.',
	'new_first_cont_one':'Support Facebook/Twitter/instagram',
	'new_first_cont_two':'Include page, post, Fan, Interaction data over 100 items.',
	'new_first_cont_three':'Support batch add page',
	'new_first_goto':'Go to',
	'new_first_can':'can manage your page ！',
	'new_secound_title':'Favorite Posts to My Library',
	'new_secound_subtitle':'FAvorited posts will saved to “my Library”, preparing for your own effective and inspiring campaigns.',
	'new_secound_cont_one':'Top Engagement posts',
	'new_secound_cont_two':'Marketing hot-spots posts',
	'new_secound_cont_three':'Bring your inspiration',
	'new_secound_goto':'Go to',
	'new_secound_can':'can find valuable posts ！',
	'new_third_title':'Use valuable paid services',
	'new_third_subtitle':'Total number of your paid services will be calculated. OS provide more effctive tools.',
	'new_third_cont_one':'Comments sentiments analysis',
	'new_third_cont_two':'Excel, PDF and more customized report',
	'new_third_cont_three':'Page hashtages analysis.',
	'new_third_goto':'Go to',
	'new_third_can':'improve your marketing ！',
	'new_fourth_title':'Key Data Dashboard',
	'new_fourth_subtitle':'After successfully add pages, you will be able to use dashboard to monitor page’s key data.',
	'new_fourth_cont_one':'And you can switch the page through the selector on the light.',
	'new_fourth_cont_two':'Then click the below button to this page’s details view data.',
	'new_fifth_title':'Finish Guide',
	'new_fifth_subtitle':'you have completed all guides.',
	'new_fifth_goto':' Start your global social media marketing now ！！！',
	'new_fifth_cont_one':'Please add our Wechat Customer Service，we prepare a Red Packet for you ！',
	'new_fifth_ok':'OK',
	//导出PDF
	AlertPDf_title:'Export Report',
	AlertPDf_title_small:"1-step export page's report,get data data overview in one sight",
	AlertPDf_main_Industry:'Industry',
	AlertPDf_main_TargetIng:'Targeting',
	AlertPDf_main_Select_RePort_type:'Select Report Type',
	AlertPDf_main_Select_RePort_Format:'Select file format',
	AlertPDf_main_EcportDataInclude:'Export Data Format',
	AlertPDf_main_RePort_Time:'Export Data Include',
	AlertPDf_main_ExPort:'Export',
	AlertPDf_footer_Am:"I'm Admin",
	AlertPDf_footer_Data:'to get more insughts data',
	AlertPDf_footer_auth:"connect Facebook",
	AlertPDf_ExportType_Operational:"Page Operation Report",
	AlertPDf_ExportType_post:"Page Posts Report",
	AlertPDf_ExportType_OperationalAuth:"Page Operation Report（Authorized）",
	AlertPDf_ExportType_postAuth:"Page Posts Report（Authorized）",
	AlertPDf_ExportType_FanPortraitAuth:"Page Fans Portrayal Report（Authorized）",
	AlertPDf_ExportType_Competitive:"Page Competitor Report",
	AlertPDf_ExportType_DownNum:"Download report quantity record this month",
	AlertPDf_ExportType_frequency:"frequency",
	AlertPDf_ExportType_HistoryExport:"View historical report",
	AlertPDf_ExportType_AdvisoryService:"Advisory Service",
	AlertPDf_ExportType_ErrorNotAuth:"Export authorization data after authorization on the home page",
	AlertPDf_ExportType_ErrorNotpayment:"Use after payment",
	AlertPDf_ExportType_Add1page:"Add the first homepage",
	AlertPDf_ExportType_Add2page:"Add a second homepage",
	AlertPDf_ExportType_Add3page:"Add a third homepage",
	AlertPDf_ExportType_SelectExportRange:"Select export range",
	AlertPDf_ExportType_SelectTimePostNum:"The total number of posts in the selected range",
	AlertPDf_ExportType_article:"article",
	AlertPDf_ExportType_ExportAll:"Export all",
	AlertPDf_ExportType_ExportNum:"Export",
	AlertPDf_ExportType_ExportTo:"to",
	//
	Export_title:"Export Report Management",
	Export_title_time:"Valid Until",
	Export_title_money:"Purchase",
	Export_main_title:"Export Report History（Latest 30 Days）",
	Export_main_Numbering:"No.",
	Export_main_ReportTopic:"Report Subject",
	Export_main_format:"Format",
	Export_main_BuildDate:"Generated Data",
	Export_main_operating:"Operation",
	Export_main_loading:"Download",
	Export_footer_moreanswer:"More Questions?",
	Export_footer_left:'1. Please seach "OneSightSupport" through Wechat to add your dedicated customer service.',
	Export_footer_leftnswer:"2. And note your message as like: ask paid service support, after success , any questions will be ok.",
	Export_footer_small:"*OneSight customer service will ask your account information to check your security certificate, you have to provide your register number or e-mail address.",
	Export_footer_scan_it:"Scan to Add Wechat Customer Service",
	Export_prompt:"To download Insight data for pagr admins, please go to Facebook to authorize data.",
	// InsAuthorize Ins主页转化为商家主页
	'InsAuthorize_header':'Facebook 主页关联到 Instagram 业务帐户详细步骤指引',
	'InsAuthorize_Instagram_API':'由于 Facebook 官方限制，Instagram 商家账户必须与 Facebook 公共主页关联， 才能够使用 Instagram API;',
	'InsAuthorize_step':'步骤如下',
	'InsAuthorize_step_one':'进入自己的 Facebook 账号中已创建的公共主页(公共主页，非您自己的 Facebook 首页，如果没有您需要先创建一个 Facebook 公共主页)。',
	'InsAuthorize_step_two':'进入公共主页，点击“设置”。',
	'InsAuthorize_step_three':'进入设置页面后，然后点击常规选项中的“Instagram”。',
	'InsAuthorize_step_fore':'点击“登录”，登录您想要添加至 OneSight 主页列表的 Instagram 帐号。',
	'InsAuthorize_step_five':'成功登录后，会出现“设置商家主页”弹窗，点击继续，并完善您想在 Instagram 商家主页上显示的基本信息。填写完成后，点击完成即成功绑定。',
	'InsAuthorize_step_sex':'成功关联成功后，就可以在 OneSight 添加该 Instagram 主页了。',
	//Download
	'Download_page_success':'Successfully',   
	'Download_page_closeWindow':'Done',
	'Download_page_AginPDF':'Re-Export',
	'Download_page_Error':'Export Error',
	'Download_page_Time':'We are working hard to export, please wait for 1 min.',
	'Download_page_NOcloseWindow':'Please don‘t close this windows.',
	'Download_page_UnderReview':'Your application is under review, please be patient',
	'Download_page_UnderReviewBtn':'I know',
	// 对比
	'start_compare': 'Compare',
	'cancel_compare': 'Cancel',
	'a_period': 'A Period',
	'b_period': 'B Period',
	// 绑定第三方账号
	'bound_accounts': 'Connected Account',
	'bind_remove': 'Remove',
	'bind_account': 'Connect to Other Third-Party',
	'only_bind_one_facebook_account': 'Each account can only be bound to one facebook account. If you want to bind a new facebook account, please remove the bound account first.',
	'only_bind_one_twitter_account': 'Each account can only be bound to one twitter account. If you want to bind a new twitter account, please remove the bound account first.',
	'only_bind_one_linkedin_account': 'Each account can only be bound to one linkedin account. If you want to bind a new linkedin account, please remove the bound account first.',
	'remove_account_content': 'After removing the third-party account binding, you cannot continue to use the account to log in to the third-party account. Are you sure to remove the account?',
	'bound_by_other_account_title': ' is already connected to another Buffer account',
	'bound_by_other_account_content': 'Each social account can only be tied to one OneSight account for security reasons.Please check if you have used another account to authorize. If you still have questions, please call customer service at 010-85818058.',
	// linkedin-主页详情
	'pagedetail_aboutus': 'About',
	'pagedetail_company_size': 'Company Size',
	'pagedetail_company_specialties': 'Specialties',
	// linkedin-主页详情-招聘数趋势
	'pagedetail_recruitment_trend': 'Number of Job Opening',
	'pagedetail_trend_table_line_CurrentRecruitmentNumber': 'Current Job Opening',
	'pagedetail_trend_table_line_MaxPerDayRecruitNum':'Max Job Opening',
	'pagedetail_trend_table_line_MinPerDayRecruitNum':'Min Job Opening',
	// linkedin-主页详情-招聘数趋势-悬浮框
	'tooltip_recruitment_trend': 'The number of job opening posted on LinkedIn.',
	// linkedin-主页详情-招聘数趋势-右侧tip
	'tip_recruitment_trend': 'The number of job opening posted on LinkedIn.',
	// linkedin-主页详情-在线员工数趋势
	'pagedetail_recruitment_peopleNum': 'Number of Employees',
	'tip_recruitment_peopleNum': 'The number of employees on Linkedin of this company',
	'tooltip_recruitment_peopleNum': 'The number of employees on Linkedin of this company',
	'pagedetail_trend_table_line_CurrentpeopleNum': 'Current Employees',
	'pagedetail_trend_table_line_MaxpeopleNum':'Max Employees',
	'pagedetail_trend_table_line_MinpeopleNum':'Min Employees',
	// linkedin-主页详情-发帖及帖文互动
	'pagedetail_trend_table_line_MostPopularPost': 'Max Engagements Post',
	'pagedetail_trend_table_line_MostUnpopularPost': 'Min Engagements Post',
	'pagedetail_asterisk_tip': '*The data is limited because the stability of system and Linkedin, please feel free to contact us if you have any question.',
	"AddPage_linkedIn_padding":"Page added successfully, data downloading…", 
	"AddPage_linkedIn_NoHaveFont":'The url must include /company, ex:https://www.linkedin.com/company/onesighttech/", "AddPage_linkedIn_NoHavePage”:”There is no company page on Linkedin, please re-add.', 
	"AddPage_linkedIn_NoHavePage":"There is no company page on Linkedin, please re-add.",
	"AddPage_linkedIn_AddPageAgin":"Page already added.",
	"AddPage_linkedIn_AddPageCount":"Only 2 brands are allowed to be observed for OneSight free users.",
	"AddPage_linkedIn_EntryLink":"Enter page url …",
	"AddPage_linkedIn_BtnDataPadding":"Data Downloading…",
	"AddPage_linkedIn_BtnDelete":"Delete",
	"AddPage_linkedIn_BtnAddPage":"Add",
	"AddPage_linkedIn_AddSomePageCallMy":"If you want to add more LinkedIn pages, please feel free to contact Wechat Customer Service or Call 010-85818058.",
	//linebarchart smalltext
	'Small_engagements':'engagements',
	"common_now_noData": "No Data",
	// 增长工具新增弹窗
	"IncreaseTool_add_Img_Info_title": "Your application was approved!",
	"IncreaseTool_add_Img_Info_PayReminderWrapIN": "Go to",
	"IncreaseTool_add_Img_Info_PayReminderWrapAnalytics": "Data Analytics",
	"IncreaseTool_add_Img_Info_PayReminderWrapDefilt": "Page Details",
	"IncreaseTool_add_Img_Info_PayReminderWrapPDF": "Download Report",
	"IncreaseTool_add_Img_Info_PayReminderWrapGo": "to get report",
	"IncreaseTool_add_Img_Info_Page": "Page",
	"IncreaseTool_add_Img_Info_Download": "Download Report",
}
export default en_US;