const zh_CN = {
	// 头部导航栏
	'header_analytics': '数据分析',
	'header_inspiration': '内容灵感',
	'header_global_list': '全球榜单',
	'header_dashboard': '管理看板',
	'header_insight': '大品牌洞察',
	'header_tools': '增长工具',
	'header_diagnosis': '运营诊断',
	'header_my_material': '素材库',
	'header_FAQ': '常见问题',
	'header_os_Rating': 'OS评分',
	'header_my_message': '我的消息',
	'header_my_info': '账号信息',
	'header_wechat_service': '微信客服',
	'header_exit': '退出',	
	// 分析-平台导航区
	'pfnav_choose_platform': '选择平台：',
    'pfnav_facebook_homepage_list': 'Facebook主页列表',
    'pfnav_twitter_homepage_list': 'Twitter主页列表',
	'pfnav_instagram_homepage_list': 'Instagram主页列表',
	'pfnav_linked_homepage_list': 'LinkedIn主页列表',
	'pfnav_youtube_homepage_list': 'YouTube主页列表',
    'pfnav_my_homepage_list': '我的主页列表',
    'pfnav_browse_by_brand': '按品牌浏览',
    'pfnav_browse_by_country': '按国家浏览',
    'pfnav_browse_by_color': '按主页标签浏览',
    'pfnav_homepage_detail': '主页详情',
	'pfnav_post_detail': '帖文详情',
	'pfnav_addpage': '添加主页',
	// 分析-列表区
	'pagetable_analytics': '数据分析',	
	'pagetable_thead_homepage':'主页',
	'pagetable_thead_brand':'品牌',
	'pagetable_thead_country':'国家/地区',
	'pagetable_thead_grade':'评分',
	'pagetable_thead_fans':'粉丝数',
	'pagetable_thead_posts': '发帖',
	'pagetable_thead_addfans':'新增粉丝数',
	'pagetable_thead_jobvacancy':'招聘职位数',
	'pagetable_thead_online':'在线职员数',
	'pagetable_thead_subscriber':'订阅者',
	'pagetable_thead_postvideos':'发布视频',
	'facebook_thead_active_engagement':'互动数',
	'facebook_thead_active_mood':'心情数',
	'facebook_thead_active_share':'分享数',
	'facebook_thead_active_comment':'评论数',
	'twitter_thead_active_engagement':'互动数',
	'twitter_thead_active_like':'喜欢数',
	'twitter_thead_active_transpond':'转发数',
	'twitter_thead_active_reply':'回复数',
	'ins_thead_active_engagement':'互动数',
	'ins_thead_active_givelike':'点赞数',
	'ins_thead_active_comment':'评论数',
	'facebook_thead_topic':'发帖',
	'facebook_thead_topic_text':'文字',
	'facebook_thead_topic_picture':'图片',
	'facebook_thead_topic_video':'视频',
	'facebook_thead_topic_link':'链接',
	'facebook_thead_topic_other':'其他',
	'twitter_thead_topic':'发帖',
	'twitter_thead_topic_text':'文字',
	'twitter_thead_topic_picture':'图片',
	'twitter_thead_topic_video':'视频',
	'ins_thead_topic':'发帖',
	'ins_thead_topic_picture':'图片',
	'ins_thead_topic_video':'视频',
	'ins_thead_topic_slide':'轮播',
	'pagetable_thead_more_operate':'操作',
	'page_first_load_tip': '数据初次加载需要24小时，请稍后查看',
	// 分析-标签管理
	'title_current_tags':'当前主页标签',
	'title_add_tags':'添加主页标签',
	'input_new_tag':'输入新标签',
	'btn_add_tag':'添加',
	'btn_tag_sure':'确定',
	'add_tag_warn_only12':'仅限12个字符',
	'add_tag_warn_repeat':'标签不能重复',
	'add_tag_warn_max3':'最多3个标签',
	'page_no_tags_left':'为',
	'page_no_tags_right':'添加一个主页标签吧',
	'chose_alltags':'全部主页',
	'chose_notags':'暂无标签',
	'select_tags':'选择主页标签',
	// 分析-添加页面 AddPage
	'add_page_ins_tips':'Ins主页添加不成功？来看看如何将你的个人Ins主页转化为商家主页',
	'add_page_please_add': '请添加',
	'add_page_add_homepage_to_my_list': '添加主页到我的列表',
	'add_linkedInpage_prompt': '免费用户可添加2个品牌主页，输入链接即可加入列表。',
    'add_page_choose_long_term_concern': '选择需要长期关注的品牌，点击添加即可加入列表。',
	'add_page_search_by_brand': '按品牌搜索',
	'add_page_search_by_link': '按链接搜索',
	'add_page_search_by_industry': '按行业搜索',
	'add_page_choose_one_level_industry': '请选择一级行业',
	'add_page_admin_add_multiple_pages': '我是管理员，批量添加我管理的主页',
	'add_page_recent_popular_pages': '最近上升最快',
	'add_page_notfound_this_homepage': '没有找到该主页，请重新输入主页链接。',
	'add_page_unable_get_valid_page_link': '找不到有效的主页链接？',
	'add_page_click_here': '点击这里',
	'add_page_learn_more': '了解更多',
	'add_paged_add': '添加',
	'add_paged_added': '已添加',
	// 分析-主页详情-头部
	'pagedetail_tag':'标签',
	'pagedetail_alias': '备注',
	'pagedetail_null': '无',	
	'pagedetail_summary': '简介',
	'pagedetail_add_to_pagelist': '+ 添加至我的主页列表',
	'pagedetail_adding_to_pagelist': '添加中...',
	'pagedetail_added_to_pagelist': '已添加到我的列表',
	'pagedetail_clerk': '职员',
	// 分析-主页详情-总览
	'pagedetail_title_admin':'我是管理员，',
	'pagedetail_title_auth':'去授权',
	'pagedetail_title_getmoredata':'获取更多数据',
	'pagedetail_pandect': '总览',
	'pagedetail_postoverview':'帖文概览',
	'pagedetail_postGood':'最好帖文',
	'pagedetail_postlow':'最差帖文',
	'pagedetail_postlist':'帖文列表',
	'pagedetail_impression':'授权',
	'pagedetail_click':'点击',
	'pagedetail_negative':'消极操作',
	'pagedetail_fanverview':'总览',
	'pagedetail_Fansportrait':'画像分析',
	'pagedetail_data_overview': '数据表现',
	'pagedetail_title_industry': '行业',
	'pagedetail_fans_top': '粉丝第',
	'pagedetail_growth_of_fans': '新增粉丝',
	'pagedetail_posts': '发帖',
	'pagedetail_compare_front_compare': '较前',
	'pagedetail_compare_front_days': '天',
	'pagedetail_thousand_interaction': '千人互动',
	'pagedetail_single_post_interaction': '单帖互动',
	'pagedetail_top_post_interaction': '最热帖文互动',
	'pagedetail_view_top_post': '查看最热帖文',
	'pagedetail_page_info': '主页信息',
	'pagedetail_page_id': '主页ID',
	'pagedetail_page_web': '主页地址',
	'pagedetail_brand': '品牌',
	'pagedetail_industry': '所属行业',
	'pagedetail_car': '汽车-汽车制造',
	'pagedetail_target_market': '目标市场',
	'pagedetail_website': '网站',
	'pagedetail_page_age': '页面年龄',
	'pagedetail_years': '年',
	'pagedetail_HQaddress': '总部所在地',
	'pagedetail_jobVacancy': '招聘职位',
	'pagedetail_clerkNumber': '职员数',
	// 分析-主页详情-帖文
	'pagedetail_post': '帖文',
	'pagedetail_spread': '展开',
	'pagedetail_collect_post': '收藏帖文',
	'pagedetail_collect_video': '收藏视频',
	'pagedetail_collected': '已收藏',
	'pagedetail_post_engagement': '互动',
	'pagedetail_post_mood': '心情',
	'pagedetail_post_share': '分享',
	'pagedetail_post_comment': '评论',
	'pagedetail_post_like': '喜欢',
	'pagedetail_post_transpond': '转发',
	'pagedetail_post_reply': '回复',
	'pagedetail_post_linkedlike': '点赞',
	'pagedetail_post_comments': '评论',
	'pagedetail_post_and_post_engagement': '发帖及帖文互动',
	'pagedetail_trend_table_line_SumPost':'总计发帖',
	'pagedetail_trend_table_line_MaxPost':'最大单日发帖',
	'pagedetail_trend_table_line_MinPost':'最小单日发帖',
	'pagedetail_trend_table_line_AvgPost':'平均单日发帖',
	'pagedetail_trend_table_line_SumEngagement':'总计互动',
	'pagedetail_trend_table_line_MaxEngagement':'最大单日互动',
	'pagedetail_trend_table_line_MinEngagement':'最小单日互动',
	'pagedetail_trend_table_line_AvgEngagement':'平均单日互动',
	'pagedetail_post_num_by_type':'发帖数量（按类型细分）',
	'pagedetail_post_type': '帖文类型',
	'pagedetail_post_num': '帖文数量',
	'pagedetail_post_num_ratio': '发帖数量占比',
	'pagedetail_photo':'图片',
	'pagedetail_video':'视频',
	'pagedetail_status':'文字',
	'pagedetail_link':'链接',
	'pagedetail_other':'其他',
	'pagedetail_post_list': '帖文列表',
	'pagedetail_post_time': '时间',
	'pagedetail_post_content': '内容',
	'pagedetail_post_collect': '收藏',
	'pagedetail_type': '类型',	
	'pagedetail_click_show_more': '展开更多',
	'pagedetail_post_list_tip': '帖文发布时间已由 UTC +00:00自动转换为您所在时区的时间。例如，您在中国，则显示的发帖时间已自动+8小时（UTC +08:00）。',
	// 分析-主页详情-粉丝
	'pagedetail_fan': '粉丝',
	'pagedetail_chart_title_Fans': '粉丝',
	'pagedetail_trend_table_line_CurrentFansNum':'当前粉丝数',
	'pagedetail_trend_table_line_MaxPerDayFansNum':'最大单日粉丝数',
	'pagedetail_trend_table_line_MinPerDayFansNum':'最小单日粉丝数',
	'pagedetail_chart_title_FansGrowth': '粉丝增长',
	'pagedetail_trend_table_line_TotalFansNum':'总计粉丝增长数',
	'pagedetail_trend_table_line_MaxPerDayFansGrowthNum':'最大单日粉丝增长数',
	'pagedetail_trend_table_line_MinPerDayFansGrowthNum':'最小单日粉丝增长数',
	'pagedetail_trend_table_line_AvgPerDayFansGrowthNum':'平均单日粉丝增长数',
	'pagedetail_trend_table_line_FansGrowthType':'粉丝增长（按类型）',
	'pagedetail_trend_table_line_AgainUseAccount':'重新启用账户',
	'pagedetail_trend_table_line_DynamicMessage':'动态消息',
	'pagedetail_trend_table_line_YourHomePage':'你的主页',
	'pagedetail_chart_title_FansDecrease': '粉丝流失',
	'pagedetail_trend_table_line_TotalFansDecreaseNum':'总计粉丝流失数',
	'pagedetail_trend_table_line_MaxPerDayFansDecreaseNum':'最大单日粉丝流失数',
	'pagedetail_trend_table_line_MinPerDayFansDecreaseNum':'最小单日粉丝流失数',
	'pagedetail_trend_table_line_AvgPerDayFansDecreaseNum':'平均单日粉丝流失数',
	'pagedetail_chart_title_FansDecreaseType': '粉丝流失（按类型）',
	'pagedetail_trend_table_line_RemoveInvalidAccount':'移出无效或停用账户',
	'pagedetail_trend_table_line_CancelPagePraise':'取消对主页或帖文的赞',
	'pagedetail_trend_table_line_FansDecreaseOther':'其他',
	'pagedetail_chart_title_FansTime':'粉丝在线时间',
	'pagedetail_chart_title_FansGrowthAndPostEngagement': '粉丝增长及帖文互动',
	'pagedetail_trend_table_line_MaxFansChange':'最大粉丝变化',
	'pagedetail_trend_table_line_MaxFansChangeCurrentDayEngagement':'最大粉丝变化当日互动',
	'pagedetail_trend_table_line_PostEngagement': '帖文互动',
	'pagedetail_fansTable_title_rank':"排名",
	'pagedetail_fansTable_title_country':"国家",
	'pagedetail_fansTable_title_impressions':"主页曝光人数",
	'pagedetail_fansTable_title_impressions_percentage':"占比",
	'pagedetail_fansTable_title_growth_rate':"增长率",
	'pagedetail_fansTable_title_fans_count_lifetime':"当地粉丝数",
	'pagedetail_fansTable_title_percentage':"占比",
	'pagedetail_fansTable_title_fans_diff':"粉丝增长数",
	//粉丝时间Y轴星期
	'PageDetail_fantime_Sunday':'星期日',
	'PageDetail_fantime_Monday':'星期一',
	'PageDetail_fantime_Tuesday':'星期二',
	'PageDetail_fantime_Wednesday':'星期三',
	'PageDetail_fantime_Thursday':'星期四',
	'PageDetail_fantime_Friday':'星期五',
	'PageDetail_fantime_Saturday':'星期六',
	// 分析-主页详情-粉丝-悬浮框
	'tooltip_fans': '在所选时间范围内，主页粉丝的总人数。',
	'tooltip_fans_growth': '在所选时间范围内，主页粉丝增加的人数。',
	'tooltip_fans_growth_by_type': '在所选时间范围内，主页粉丝增加的人数，按粉丝增长类型细分。',
	'tooltip_fans_decrease': '在所选时间范围内，主页粉丝流失的人数。',
	'tooltip_fans_decrease_by_type': '在所选时间范围内，主页粉丝流失的人数，按粉丝流失类型细分。',
	'tooltip_fans_growth_and_post_engagement': '在所选时间范围内，主页粉丝增长及帖文互动的关联性变化。',
	'tooltip_fansTime': '在所选时间范围内，各时段主页粉丝在Facebook上活跃的人数。',
	// 分析-主页详情-粉丝-右侧tip
	'tip_fans': '主页粉丝的总人数。',
	'tip_fans_growth': '主页粉丝增加的人数。',
	'tip_fans_growth_by_type': '主页粉丝增加的人数，按粉丝增长类型细分。',
	'tip_fans_decrease': '主页粉丝流失的人数。',
	'tip_fans_decrease_by_type': '主页粉丝流失的人数，按粉丝流失类型细分。',
	'tip_fans_growth_and_post_engagement': '主页粉丝增长及帖文互动的关联性变化。',
	'tip_fansTime': '各时段主页粉丝在Facebook上活跃的人数。',
	// 分析-主页详情-互动
	'pagedetail_engagement': '互动',
	'pagedetail_interaction': '互动',
	'pagedetail_chart_title_PostEngagementByType':'帖文互动（按类型）',
	'pagedetail_chart_title_ThsEngagementByType':'千人互动',
	'pagedetail_chart_title_SingleEngagement':'单帖互动',
	'pagedetail_chart_title_PositiveOperatorNum': '积极操作次数（按类型）',
	'pagedetail_trend_table_line_AnswerUserQuestion':'回答用户问题',
	'pagedetail_trend_table_line_Link':'链接',
	'pagedetail_trend_table_line_Mood':'心情',
	'pagedetail_chart_title_NegativeOperatorNum': '消极操作次数（按类型）',
	'pagedetail_trend_table_line_HideAllPosts':'隐藏全部帖子',
	'pagedetail_trend_table_line_ClosePage':'关闭主页',
	'pagedetail_trend_table_line_ReportJunkInfo':'举报垃圾信息',
	'pagedetail_chart_title_PostEngagementRatio': '帖文互动比例',
	'pagedetail_chart_title_MoodRatio': '心情比例',
	'pagedetail_chart_title_PageClickNumRatio': '主页点击次数比例',
	'pagedetail_chart_title_PositiveOperatorRatio': '积极操作次数比例',
	'pagedetail_chart_title_NegativeOperatorRatio': '消极操作次数比例',
	// 分析-主页详情-互动-悬浮框
	'tooltip_post_engagement_by_type': '在所选时间范围内，主页发布的帖文所获得的互动次数，即心情+分享+评论。',
	'tooltip_tw_post_engagement_by_type': '在所选时间范围内，主页发布的帖文所获得的互动次数，即喜欢+转发+回复。',
	'tooltip_ins_post_engagement_by_type': '在所选时间范围内，主页发布的帖文所获得的互动次数，即点赞+评论。',
	'tooltip_thousand_fans_engagement': '在所选时间范围内，平均每1000个粉丝可获得的帖文互动数。即帖文互动数/总粉丝数*1000。（总计千人互动数：总计千人互动数为所选日期范围内，每一单日的千人互动数相加。）',
	'tooltip_single_post_engagement': '在所选时间范围内，平均每个帖文可获得的帖文互动数。即所选日期范围内的帖文互动数/所选日期范围内的发帖数。',
	'tooltip_positive_operator_num_by_type': '在所选时间范围内，用户对主页进行积极操作的次数。按积极操作类型细分。',
	'tooltip_negative_operator_num_by_type': '在所选时间范围内，用户对主页进行积极操作的次数。按消极操作类型细分。',
	'tooltip_post_engagement_ratio': '在所选时间范围内，各类型的帖文互动次数占帖文互动总次数的比例。',
	'tooltip_mood_ratio': '在所选时间范围内，各类型的心情次数占心情总次数的比例。',
	'tooltip_page_click_num_ratio': '在所选时间范围内，各类型的主页内容被点击次数占点击总次数的比例。',
	'tooltip_positive_operator_ratio': '在所选时间范围内，各类型的积极操作次数占积极操作总次数的比例。',
	'tooltip_negative_operator_ratio': '在所选时间范围内，各类型的消极操作次数占消极操作总次数的比例。',
	'tooltip_ossScore':'OS 评分根据您主页的粉丝、粉丝增长、发帖、帖文互动和千人互动进行的评分。',
	'tooltip_insossScore':'OS 评分根据您主页的粉丝、粉丝增长、发帖和帖文互动进行的评分。',
	'tooltip_post_and_engagement':'主页发布的帖文及帖文所获帖文互动的关联性变化。',
	// 分析-主页详情-互动-右侧tip
	'tip_post_engagement_by_type': '主页发布的帖文所获得的互动次数，即心情+分享+评论。',
	'tip_tw_post_engagement_by_type': '主页发布的帖文所获得的互动次数，即喜欢+转发+回复。',
	'tip_ins_post_engagement_by_type': '主页发布的帖文所获得的互动次数，即点赞+评论。',
	'tip_thousand_fans_engagement': '平均每1000个粉丝可获得的帖文互动数。即帖文互动数/总粉丝数*1000。',
	'tip_single_post_engagement': '平均每个帖文可获得的帖文互动数。即所选日期范围内的帖文互动数/所选日期范围内的发帖数。',
	'tip_positive_operator_num_by_type': '用户对主页进行积极操作的次数。按积极操作类型细分。',
	'tip_negative_operator_num_by_type': '用户对主页进行消极操作的次数。按消极操作类型细分。',
	'tip_post_engagement_ratio': '各类型的帖文互动次数占帖文互动总次数的比例。',
	'tip_mood_ratio': '各类型的心情次数占心情总次数的比例。',
	'tip_page_click_num_ratio': '各类型的主页内容被点击次数占点击总次数的比例。',
	'tip_positive_operator_ratio': '各类型的积极操作次数占积极操作总次数的比例。',
	'tip_negative_operator_ratio': '各类型的消极操作次数占消极操作总次数的比例。',
	// 分析-主页详情-曝光
	'pagedetail_exposure': '曝光',
	'pagedetail_chart_title_PageAndPostExposureNum':'主页曝光次数及帖文曝光次数',
	'pagedetail_trend_table_line_TotalPageExposureNum':'总计主页曝光次数',
	'pagedetail_trend_table_line_MaxPerDayPageExposure':'最大单日主页曝光',
	'pagedetail_trend_table_line_MinPerDayPageExposure':'最小单日主页曝光',
	'pagedetail_trend_table_line_AvgPerDayPageExposure':'平均每日主页曝光',
	'pagedetail_trend_table_line_AvgPageExposureFrequency':'平均主页曝光频次',
	'pagedetail_trend_table_line_TotalPostExposureNum':'总计帖文曝光次数',
	'pagedetail_trend_table_line_MaxPerDayPostExposure':'最大单日帖文曝光',
	'pagedetail_trend_table_line_MinPerDayPostExposure':'最小单日帖文曝光',
	'pagedetail_trend_table_line_AvgPerDayPostExposure':'平均每日帖文曝光',
	'pagedetail_trend_table_line_AvgPostExposureFrequency':'平均帖文曝光频次',
	'pagedetail_chart_title_PageExposureNumRatio':'主页曝光次数比例',
	'pagedetail_chart_title_PostExposureNumRatio':'帖文曝光次数比例',
	'pagedetail_chart_title_PageExposureNumOfPeopleDistribution':'主页曝光人数国家分布',
	// 分析-主页详情-曝光-悬浮框
	'tooltip_PageAndPostExposureNum':'在所选时间范围内，主页及帖文各自获得的曝光次数和推广效果。（主页曝光：任意主页内容出现在用户设备屏幕中的次数，例如签到、广告等。帖文曝光：您的主页帖文出现在用户设备屏幕中的次数，例如照片、链接、视频等。）',
	'tooltip_PageExposureNumRatio':'在所选时间范围内，付费主页曝光次数及自然主页曝光次数占帖文曝光总次数的比例。',
	'tooltip_PostExposureNumRatio':'在所选时间范围内，付费帖文曝光次数及自然帖文曝光次数占帖文曝光总次数的比例。',
	'tooltip_PageExposureNumOfPeopleDistribution':'在所选时间范围内，主页曝光人数的国家分布。',
	'tooltip_post_impressions':'帖文曝光次数',
	'tooltip_page_impressions':'主页曝光次数',
	// 分析-主页详情-曝光-右侧tip
	'tip_PageAndPostExposureNum':'主页及帖文各自获得的曝光次数和推广效果。',
	'tip_PageExposureNumRatio':'付费主页曝光次数及自然主页曝光次数占帖文曝光总次数的比例。',
	'tip_PostExposureNumRatio':'付费帖文曝光次数及自然帖文曝光次数占帖文曝光总次数的比例。',
	'tip_PageExposureNumOfPeopleDistribution':'主页曝光人数的国家分布。',
	// 分析-主页详情-视频
	'pagedetail_video': '视频',
	'pagedetail_chart_title_post_video_time_watched':'视频观看时长',
	'pagedetail_chart_title_Video_Views':'视频观看次数',
	'pagedetail_chart_title_Video_Proportion':'视频观看次数比例',
	'pagedetail_chart_title_VideoWatchTimesFunnel':'视频观看次数漏斗',
	'pagedetail_chart_title_VideoPlayRatio':'视频播放操作比例',
	'pagedetail_trend_table_line_VideoTimeSum':'总计视频观看时长',	
	'pagedetail_trend_table_line_VideoTimeMax':'最大单日视频观看时长',	
	'pagedetail_trend_table_line_VideoTimeMin':'最小单日视频观看时长',	
	'pagedetail_trend_table_line_VideoTimeAvg':'平均每日视频观看时长',	
	'pagedetail_trend_table_line_VideoViewsSum':'总计视频观看次数',	
	'pagedetail_trend_table_line_VideoViewsMax':'最大单日视频观看次数',	
	'pagedetail_trend_table_line_VideoViewsMin':'最小单日视频观看次数',	
	'pagedetail_trend_table_line_VideoViewsAvg':'平均每日视频观看次数',
	// 分析-主页详情-视频-悬浮框
	'tooltip_post_video_time_watched': '在所选时间范围内，主页发布的视频被用户观看的时长。',
	'tooltip_Video_Views': '主页发布的视频被用户观看的时长。',
	'tooltip_Video_Proportion': '在所选时间范围内，付费视频观看次数及自然视频观看次数占视频观看总次数的比例。',
	'tooltip_VideoWatchTimesFunnel': '在所选时间范围内，付费视频观看次数及自然视频观看次数的留存量及占比。',
	'tooltip_VideoPlayRatio': '在所选时间范围内，用户观看主页发布的视频所采用的操作，按用户操作类型细分。',
	'tooltip_page_video_views_organic':'自然视频观看次数',
	'tooltip_page_video_views_paid':'付费视频观看次数',
	'tooltip_page_video_views_autoplayed':'自动播放',
	'tooltip_page_video_views_click_to_play':'点击播放',
	// 分析-主页详情-视频-右侧tip
	'tip_post_video_time_watched': '主页发布的视频被用户观看的时长。',
	'tip_Video_Views': '主页发布的视频被用户观看超过3秒的次数。',
	'tip_Video_Proportion': '付费视频观看次数及自然视频观看次数占视频观看总次数的比例。',
	'tip_VideoWatchTimesFunnel': '付费视频观看次数及自然视频观看次数的留存量及占比。',
	'tip_VideoPlayRatio': '用户观看主页发布的视频所采用的操作，按用户操作类型细分。',
	// 分析-主页详情-粉丝画像
	'pagedetail_fans_portrait': '粉丝画像',
	'pagedetail_chart_title_GenderAndAge':'粉丝性别年龄分布',
	'pagedetail_chart_title_FansCountryDistribution': '粉丝国家分布',
	'pagedetail_chart_title_FansGrowthCountryDistribution': '粉丝增长国家分布',
	'male': "男性",
	'female': '女性',
	'a_period_male': 'A组男性',
	'a_period_female': 'A组女性',
	'b_period_male': 'B组男性',
	'b_period_female': 'B组女性',
	'view_more': '点击查看更多',
	// 分析-主页详情-粉丝画像-悬浮框
	'tooltip_GenderAndAge': '在所选时间范围内，主页粉丝的性别与年龄分布。',
	'tooltip_FansCountryDistribution': '在所选时间范围内，主页粉丝的国家分布。',
	'tooltip_FansGrowthCountryDistribution': '在所选时间范围内，主页粉丝增长的国家分布。',
	// 分析-主页详情-粉丝画像-右侧tip
	'tip_GenderAndAge': '主页粉丝的性别与年龄分布。',
	'tip_FansCountryDistribution': '主页粉丝的国家分布。',
	'tip_FansGrowthCountryDistribution': '主页粉丝增长的国家分布。',
	// 分析-主页详情-内容
	'pagedetail_content': '内容',
	// 分析-主页详情-主页
	'pagedetail_noauth_tip':'此数据为授权数据，授权后即可查看',
	'pagedetail_page': '主页',
	'pagedetail_trend_table_line_Max':'最大',
	'pagedetail_trend_table_line_Min':'最小',
	'pagedetail_trend_table_line_Avg':'平均',
	'pagedetail_trend_table_line_Value':'总计',
	'pagedetail_trend_table_line_Maxfans':'最大粉丝数',
	'pagedetail_trend_table_line_Minfans':'最小粉丝数',
	'pagedetail_trend_table_line_Avgfans':'平均粉丝数',
	'pagedetail_trend_table_line_Maxtopicactive':'最大单日互动',
	'pagedetail_trend_table_line_Mintopicactive':'最小单日互动',
	'pagedetail_trend_table_line_Avgtopicactive':'平均单日互动',
	'pagedetail_trend_table_line_Maxpagescore':'最大OS评分',
	'pagedetail_trend_table_line_Minpagescore':'最小OS评分',
	'pagedetail_trend_table_line_Avgpagescore':'平均OS评分',
	'pagedetail_trend_table_line_SumPostEngagement':'总计帖文互动',
	'pagedetail_trend_table_line_MaxPostEngagement':'最大帖文互动',
	'pagedetail_trend_table_line_MinPostEngagement':'最小帖文互动',
	'pagedetail_trend_table_line_AvgPostEngagement':'平均帖文互动',
	'pagedetail_trend_table_line_SumThsEngagement':'总计千人互动数',
	'pagedetail_trend_table_line_MaxThsdayEngagement':'最大单日千人互动数',
	'pagedetail_trend_table_line_MinThsdayEngagement':'最小单日千人互动数',
	'pagedetail_trend_table_line_AvgThsdayEngagement':'平均单日千人互动数',		
	'pagedetail_trend_table_line_SumpreEngagement':'当前周期单帖互动平均数',
	'pagedetail_trend_table_line_MaxpredayEngagement':'最大单日单帖互动数',
	'pagedetail_trend_table_line_MinpredayEngagement':'最小单日单帖互动数',
	'pagedetail_trend_table_line_AvgpredayEngagement':'平均单日单帖互动数',	
	'pagedetail_trend_table_line_SumBy@':'总计被@',
	'pagedetail_trend_table_line_MaxBy@':'最大单日被@',
	'pagedetail_trend_table_line_MinBy@':'最小单日被@',
	'pagedetail_trend_table_line_AvgBy@':'平均单日被@',
	'pagedetail_trend_table_line_page_video_views_all':'视频观看',
	'pagedetail_trend_table_line_page_video_views_10':'超10秒观看',
	'pagedetail_trend_table_line_page_video_views_30':'超30秒或完整观看',
	'pagedetail_chart_title_fans':'粉丝',
	'pagedetail_chart_title_OSScore':'OS评分',	
	'pagedetail_chart_title_by@':'被@',
	'pagedetail_chart_title_PostEngagementScale':'帖文互动比例',
	'pagedetail_chart_title_alltypeEngagement':'各类帖文所获互动',
	'pagedetail_chart_title_alltypeEngagementbytype':'各类帖文所获互动(按类型)',
	'Login_with_facebook':'使用 Facebook 登录',
	// tw分析-主页详情-关注
	'pagedetail_attention': '关注',
	'pagedetail_chart_title_attention_diff': '关注增长',
	'pagedetail_chart_title_belong_list': '属于的列表',
	'pagedetail_trend_table_line_attentionCur':'当前关注',	
	'pagedetail_trend_table_line_attentionMax':'最大单日关注',	
	'pagedetail_trend_table_line_attentionMin':'最小单日关注',	
	'pagedetail_trend_table_line_SumAttentionDiff':'总计关注增长',
	'pagedetail_trend_table_line_MaxAttentionDiff':'最大单日关注增长',
	'pagedetail_trend_table_line_MinAttentionDiff':'最小单日关注增长',
	'pagedetail_trend_table_line_AvgAttentionDiff':'平均单日关注增长',
	'pagedetail_trend_table_line_belongListCur':'当前属于的列表',	
	'pagedetail_trend_table_line_belongListMax':'最大单日属于的列表',	
	'pagedetail_trend_table_line_belongListMin':'最小单日属于的列表',
	"tooltip_attention":"在所选时间范围内，主页正在关注的总人数。",
	"tip_attention":"主页正在关注的总人数。",
	"tooltip_attention_diff":"在所选时间范围内，主页正在关注增加的人数。",
	"tip_attention_diff":"主页正在关注增加的人数。",
	"tooltip_belong_list":"在所选时间范围内，主页属于的列表的总数。属于的列表：当主页被某列表收录为成员时，则主页属于该列表。",
	"tip_belong_list":"主页属于的列表的总数。属于的列表：当主页被某列表收录为成员时，则主页属于该列表。",
	// INS分析-主页详情-话题
	'pagedetail_topic': '话题',
	'pagedetail_chart_title_topic_usenum':'主页话题使用次数',
	'pagedetail_trend_table_line_SumTopic':'总计主页使用话题次数',
	'pagedetail_trend_table_line_MaxTopic':'最大单日主页使用话题次数',
	'pagedetail_trend_table_line_MinTopic':'最小单日主页使用话题次数',
	'pagedetail_trend_table_line_AvgTopic':'平均单日主页使用话题次数',
	'pagedetail_trend_table_topic_cloud':'主页话题云',	
	'pagedetail_trend_table_topic_ranking':'排名',	
	'pagedetail_trend_table_topic_usenum':'使用次数',	
	'pagedetail_trend_table_topic_active':'该话题合计帖文互动',	
	'pagedetail_trend_table_topic_seemost':'查看最多互动帖文',
	// YouTube-主页详情
	'pagelist_ytb_tip':'当前日期范围内，因发布视频数为0，暂无视频互动，您可调整时间范围寻找最近的发布视频记录。',
	'pagedetail_subscriber_text': '位订阅者',
	'pagedetail_comment': '评论人数',
	'pagedetail_growth_of_subscriber': '新增订阅者',
	'pagedetail_growth_of_video': '新增视频',
	'pagedetail_growth_of_video_view_time': '新增视频观看次数',
	'pagedetail_single_item_interaction': '单条互动',
	'pagedetail_top_video_view_time': '最热视频观看次数',
	'pagedetail_view_time': '观看次数',
	'pagedetail_total_video': '视频总数',
	'pagedetail_collect_video': '收藏视频',
	'pagedetail_top': '顶',
	'pagedetail_tread': '踩',
	'pagedetail_chart_title_SubscriberComment':"订阅者与频道观看次数",
	'tip_Ytb_SubscriberComment':"主页订阅的总人数及频道观看次数分析。",
	'tooltip_Ytb_SubscriberComment':"在所选时间范围内，主页订阅者的总人数及频道观看次数。",
	'pagedetail_trend_table_line_MaxSubscriber': '最大订阅者',
	'pagedetail_trend_table_line_MinSubscriber': '最小订阅者',	
	'pagedetail_trend_table_line_AvgSubscriber': '平均订阅者',
	'pagedetail_trend_table_line_MaxComment': '最大评论人数',
	'pagedetail_trend_table_line_MinComment': '最小评论人数',	
	'pagedetail_trend_table_line_AvgComment': '平均评论人数',
	'pagedetail_chart_title_VideoNumWatchNum':"视频数量与视频观看次数",
	'tip_Ytb_VideoNumWatchNum':"主页累计发布的视频数量与视频累计观看次数分析",
	'tooltip_Ytb_VideoNumWatchNum':"在所选时间范围内，主页订阅者的总人数及评论视频的总人数。",
	'pagedetail_trend_table_line_MaxYtbVideoNum': '最大视频数量',
	'pagedetail_trend_table_line_MinYtbVideoNum': '最小视频数量',	
	'pagedetail_trend_table_line_AvgYtbVideoNum': '平均视频数量',
	'pagedetail_trend_table_line_MaxYtbWatchNum': '最大频道观看次数',
	'pagedetail_trend_table_line_MinYtbWatchNum': '最小频道观看次数',	
	'pagedetail_trend_table_line_AvgYtbWatchNum': '平均频道观看次数',
	'pagedetail_chart_title_addVideoNum':"每日新增视频数量",
	'tooltip_Ytb_addVideoNum':"在所选时间范围内，主页发布视频的新增数量。",
	'pagedetail_chart_title_dayaddWatchNum':"每日新增视频观看次数",
	'tooltip_Ytb_addWatchNum':"在所选时间范围内，主页发布视频的新增观看次数。",
	'pagedetail_chart_title_addCommentNum':"每日新增视频时长",
	'pagedetail_chart_title_addCommentNum1':"每日新增视频时长(秒)",
	'tooltip_Ytb_addCommentNum':"在所选时间范围内，主页发布视频的获得的新增评论数。",
	'pagedetail_trend_table_line_SumYtbaddVideoNum': '总计新增视频数量',
	'pagedetail_trend_table_line_MaxYtbaddVideoNum': '最大单日新增视频数量',
	'pagedetail_trend_table_line_MinYtbaddVideoNum': '最小单日新增视频数量',	
	'pagedetail_trend_table_line_AvgYtbaddVideoNum': '平均单日新增视频数量',
	'pagedetail_trend_table_line_SumYtbaddWatchNum': '总计新增观看次数',
	'pagedetail_trend_table_line_MaxYtbaddWatchNum': '最大单日新增观看次数',
	'pagedetail_trend_table_line_MinYtbaddWatchNum': '最小单日新增观看次数',	
	'pagedetail_trend_table_line_AvgYtbaddWatchNum': '平均单日新增观看次数',
	'pagedetail_trend_table_line_SumYtbaddCommentNum': '总计新增视频时长(秒)',
	'pagedetail_trend_table_line_MaxYtbaddCommentNum': '最大单日新增视频时长(秒)',
	'pagedetail_trend_table_line_MinYtbaddCommentNum': '最小单日新增视频时长(秒)',	
	'pagedetail_trend_table_line_AvgYtbaddCommentNum': '平均单日新增视频时长(秒)',
	// YouTube-主页详情-视频
	'pagedetail_trend_table_line_VideoNum': '频道视频数量',
	'pagedetail_trend_table_line_CurrentPublishVideoNum':'当前频道视频数量',
	'pagedetail_trend_table_line_MaxPublishVideoNum':'最大频道视频数量',
	'pagedetail_trend_table_line_MinPublishVideoNum':'最小频道视频数量',
	'pagedetail_trend_table_line_GrowthVideoAndEngagement': '新增视频与所获互动',
	'pagedetail_growth_of_video': '新增视频',
	'pagedetail_trend_table_line_TotalVideos': '总计发布视频',
	'pagedetail_trend_table_line_MaxPerDayPublishVideo': '最大单日发布视频',
	'pagedetail_trend_table_line_MinPerDayPublishVideo': '最小单日发布视频',	
	'pagedetail_trend_table_line_AvgPerDayPublishVideo': '平均单日发布视频',
	'pagedetail_trend_table_line_TotalEngagement': '总计互动',
	'pagedetail_trend_table_line_MaxPerDayEngagement': '最大单日互动',
	'pagedetail_trend_table_line_MinPerDayEngagement': '最小单日互动',	
	'pagedetail_trend_table_line_AvgPerDayEngagement': '平均单日互动',
	'pagedetail_duration': '视频时长',
	// YouTube-主页详情-视频-悬浮框
	'tooltip_homepage_post_video_num': '在所选时间范围内，主页频道累计发布的视频数量',
	'tooltip_growth_video_and_engagement': '在所选时间范围内，主页发布的新增数量与视频所获互动关联性变化',
	// YouTube-主页详情-视频-右侧tip
	'tip_homepage_post_video_num': '主页频道累计发布的视频数量',
	'tip_growth_video_and_engagement': '主页发布的新增数量与视频所获互动关联性变化',
	// YouTube分析-主页详情-订阅者
	'pagedetail_subscriber':'订阅者',
	'pagedetail_total_subscriber': '订阅者',
	'pagedetail_chart_title_subscriberGrowth':'订阅者增长',
	'pagedetail_chart_title_subscriberGrowthAndVideoEngagement':'订阅者增长及互动',
	'tooltip_subscriber':'在所选时间范围内，主页订阅者的总人数。',
	'tooltip_subscriber_growth':'在所选时间范围内，主页订阅者增加的总人数。',
	'tooltip_subscriber_growth_and_video_engagement':'在所选时间范围内，主页订阅者增长及视频互动的关联性变化。',
	'tip_subscriber':'主页订阅者的总人数。',
	'tip_subscriber_growth':'主页订阅者增加的总人数。',
	'tip_subscriber_growth_and_video_engagement':'主页订阅者增长及视频互动的关联性变化。',
	'pagedetail_trend_table_line_CurrentsubscriberNum':'当前订阅者',
	'pagedetail_trend_table_line_MaxPerDaysubscriberNum':'最大单日订阅者',
	'pagedetail_trend_table_line_MinPerDaysubscriberNum':'最小单日订阅者',
	'pagedetail_trend_table_line_TotalsubscriberNum':'总计订阅者增长',
	'pagedetail_trend_table_line_MaxPerDaysubscriberGrowthNum':'最大单日订阅者增长数',
	'pagedetail_trend_table_line_MinPerDaysubscriberGrowthNum':'最小单日订阅者增长数',
	'pagedetail_trend_table_line_AvgPerDaysubscriberGrowthNum':'平均单日订阅者增长数',
	'pagedetail_trend_table_line_MaxsubscriberChange':'最大订阅者变化',
	'pagedetail_trend_table_line_MaxsubscriberChangeCurrentDayEngagement':'最大订阅者变化当日互动',
	// YouTube分析-主页详情-互动
	'pagedetail_chart_title_WatchNum':"视频观看次数",
	'pagedetail_chart_title_ViewNum':"频道观看次数",
	'pagedetail_chart_title_addWatchNum':"新增视频观看次数",
	'pagedetail_chart_title_videoEvaluate':"视频获得的顶与踩",
	'pagedetail_chart_title_videoEngagement':"视频互动（按类型）",
	'pagedetail_chart_title_ThsEngagementByType':"千人互动",
	'pagedetail_chart_title_SingleVideoEngagement':"单条互动",
	'pagedetail_chart_title_EngagementScale':"互动比例",
	'tooltip_Ytbvideo_WatchNum':"在所选时间范围内，主页发布的视频累计被用户观看的次数。",
	'tooltip_Ytbvideo_addWatchNum':"在所选时间范围内，主页发布的视频观看增长的总次数。",
	'tooltip_Ytbvideo_videoEvaluate':"在所选时间范围内，主页发布视频获得的顶与踩。",
	'tooltip_Ytbvideo_videoEngagement':"在所选时间范围内，主页发布的视频获得的总互动次数，即顶+踩+评论。",
	'tooltip_Ytbvideo_ThsEngagementByType':"在所选时间范围内，平均每1000个订阅者可获得的视频互动数。即视频互动数/总订阅者数*1000。",
	'tooltip_Ytbvideo_SingleVideoEngagement':"在所选时间范围内，平均每个视频可获得的视频互动数。即所选日期范围内的视频互动数/所选日期范围内的视频数。",
	'tooltip_Ytbvideo_EngagementScale':"在所选时间范围内，各类型的视频互动次数占视频互动总次数的比例。",
	'tip_Ytbvideo_WatchNum':"主页发布的视频累计被用户观看的次数。",
	'tip_Ytbvideo_addWatchNum':"主页发布的视频观看增长的总次数。",
	'tip_Ytbvideo_videoEvaluate':"主页发布视频获得的顶与踩。",
	'tip_Ytbvideo_videoEngagement':"主页发布的视频获得的总互动次数，即顶+踩+评论。",
	'tip_Ytbvideo_ThsEngagementByType':"平均每1000个订阅者可获得的视频互动数。即视频互动数/总订阅者数*1000。",
	'tip_Ytbvideo_SingleVideoEngagement':"平均每个视频可获得的视频互动数。即所选日期范围内的视频互动数/所选日期范围内的视频数。",
	'tip_Ytbvideo_EngagementScale':"各类型的视频互动次数占视频互动总次数的比例。",
	'pagedetail_trend_table_line_CurWatchNum':'当前观看次数',
	'pagedetail_trend_table_line_MaxWatchNum':'最大观看次数',
	'pagedetail_trend_table_line_MinWatchNum':'最小观看次数',
	'pagedetail_trend_table_line_SumVideoWatchNum':'总计视频观看次数',
	'pagedetail_trend_table_line_MaxVideoWatchNum':'最大视频观看次数',
	'pagedetail_trend_table_line_MinVideoWatchNum':'最小视频观看次数',
	'pagedetail_trend_table_line_AvgVideoWatchNum':'平均视频观看次数',
	'pagedetail_trend_table_line_SumVideoGetTop':'总计视频获得的顶',
	'pagedetail_trend_table_line_MaxVideoGetTop':'最大单日视频获得的顶',
	'pagedetail_trend_table_line_MinVideoGetTop':'最小单日视频获得的顶',
	'pagedetail_trend_table_line_AvgVideoGetTop':'平均单日视频获得的顶',	
	'pagedetail_trend_table_line_SumVideoGetTread':'总计视频获得的踩',
	'pagedetail_trend_table_line_MaxVideoGetTread':'最大单日视频获得的踩',
	'pagedetail_trend_table_line_MinVideoGetTread':'最小单日视频获得的踩',
	'pagedetail_trend_table_line_AvgVideoGetTread':'平均单日视频获得的踩',
	'pagedetail_trend_table_line_SumVideoEngagement':'总计视频互动数',
	'pagedetail_trend_table_line_MaxVideoEngagement':'最大单日视频互动',
	'pagedetail_trend_table_line_MinVideoEngagement':'最小单日视频互动',
	'pagedetail_trend_table_line_AvgVideoEngagement':'平均单日视频互动',	
	'pagedetail_trend_table_line_SumThsVideoEngagement':'总计千人互动',
	'pagedetail_trend_table_line_MaxThsVideoEngagement':'最大千人互动',
	'pagedetail_trend_table_line_MinThsVideoEngagement':'最小千人互动',
	'pagedetail_trend_table_line_AvgThsVideoEngagement':'平均千人互动',	
	'pagedetail_trend_table_line_CurSingleVideoEngagement':'当前周期单条互动平均数',
	'pagedetail_trend_table_line_MaxSingleVideoEngagement':'最大单日单条互动数',
	'pagedetail_trend_table_line_MinSingleVideoEngagement':'最小单日单条互动数',
	'pagedetail_trend_table_line_AvgSingleVideoEngagement':'平均单日单条互动数',	
	// 分析-悬浮框信息
	'tooltip_likes':'心情',
	'tooltip_post_likes':'心情',
	'tooltip_post_shares':'分享',
	'tooltip_post_comments':'评论',
	'tooltip_shares':'分享',
	'tooltip_post':'发帖',
	'tooltip_all':'全部',
	'tooltip_comments':'评论',
	'tooltip_photo':'图片',
	'tooltip_video':'视频',
	'tooltip_active':'互动',
	'tooltip_link':'链接',
	'tooltip_status':'文字',
	'tooltip_other':'其他',
	'tooltip_value':'全部',
	'tooltip_like': '赞',
	'tooltip_love': '大爱',
	'tooltip_wow': '哇',
	'tooltip_haha': '笑趴',
	'tooltip_sad': '心碎',
	'tooltip_angry': '怒',
	'facebook_tooltip_all':'全部',
	'facebook_tooltip_likes':'心情',
	'facebook_tooltip_shares':'分享',
	'facebook_tooltip_comments':'评论',
	'facebook_tooltip_active':'互动',
	'twitter_tooltip_likes':'喜欢',
	'twitter_tooltip_shares':'转发',
	'twitter_tooltip_all':'全部',
	'twitter_tooltip_comments':'回复',
	'instagram_tooltip_all':'全部',
	'instagram_tooltip_likes':'点赞',
	'instagram_tooltip_comments':'评论',
	'youtube_tooltip_likes':'顶',
	'youtube_tooltip_dislikes':'踩',
	'youtube_tooltip_comments':'评论',	
	'tooltip_hide_all_clicks':'隐藏全部帖子',
    'tooltip_hide_clicks':'隐藏帖子',
    'tooltip_comment':'评论',
    'tooltip_page_negative_feedback_by_type':'隐藏',
    'tooltip_report_spam_clicks':'举报垃圾信息',
    'tooltip_unlike_page_clicks':'取消赞',
    'tooltip_xbutton_clicks':'关闭主页',
    'tooltip_answer':'回答用户问题',
    'tooltip_claim':'索要价格',
    "tooltip_page_positive_feedback_by_type":'积极操作次数',
    "tooltip_other clicks":'其他点击',
    "tooltip_photo view":"图片点击",
    "tooltip_video play":'视频点击',
    "tooltip_link clicks":'链接点击',
    "tooltip_button clicks":'按钮点击',
    "tooltip_page_fans_by_unlike_source_unique":"",
    "tooltip_Ads":'广告',
    "tooltip_News Feed":'你的主页',
    "tooltip_Your Page":'动态消息',
    "tooltip_Page Suggestions":'主页推荐',
    "Restored Likes from Reactivated Accounts":"重新启用账户",
    "tooltip_Search":"搜索",
    "tooltip_Restored Likes from Reactivated Accounts":'重新启用账户',
    "tooltip_Deactivated or Memorialized Account Removals":'移除无效或停用账户',
    "tooltip_Unlikes from Page, Posts, or News Feed":'取消对主页或帖文的赞',
	"tooltip_Unlikes from Page Suggestions":'在推荐中取消赞',
    "tooltip_Other":'其他',
    "tooltip_Suspicious Account Removals":'移除可疑账户',
    "tooltip_Unlikes from Search":'搜索中取消赞',
    "tooltip_page_impressions_organic":'自然主页曝光次数',
    "tooltip_page_impressions_paid":'付费主页曝光次数',
    "tooltip_page_posts_impressions_organic":'自然帖文曝光次数',
    "tooltip_page_posts_impressions_paid":'付费帖文曝光次数',
	"tooltip_page_video_views_10s_autoplayed":'10s自动播放',
	"tooltip_page_video_views_10s_click_to_play":'10s点击播放',
	"tooltip_page_video_complete_views_30s_autoplayed":'30s自动播放',
	"tooltip_page_video_complete_views_30s_click_to_play":'30s点击播放',
	"tooltip_funnle_all":'总观看',
	"tooltip_funnle_10s":'超10s观看',
	"tooltip_funnle_30s":'超30s或完整观看',
	 "tooltip_os_Rating":'当前OS评分',
	//漏斗图
	'FunnleChart_SelectType_all':'总观看',
	'FunnleChart_SelectType_organic':'自然观看',
	'FunnleChart_SelectType_paid':'付费观看',
	// 灵感-导航
	'inspiration_title_Pagetypes':'帖文类型',
	'inspiration_title_Choose a specific homepage':'选择特定的主页',
	'inspiration_facebook_inspiration': 'Facebook灵感',
	'inspiration_twitter_inspiration': 'Twitter灵感',
	'inspiration_instagram_inspiration': 'Instagram灵感',
	'inspiration_youtube_inspiration': 'YouTube灵感',
	'inspiration_linkedin_inspiration': 'Linkedin灵感',
	'inspiration_square': '灵感广场',
	'inspiration_recentposts': '最新帖文',
	'inspiration_popularposts': '最热帖文',
	'inspiration_hottestposts':'最热帖文',
	'inspiration_prefersharingposts': '更有分享意愿帖文',
	'inspiration_positiveposts': '积极情绪倾向帖文',
	'inspiration_negativeposts': '消极情绪倾向帖文',
	'inspiration_recentvideos':'最新视频',
	'inspiration_hottestvideos':'最多互动视频',
	'inspiration_mostviewsvideos':'最多视频观看',
	'inspiration_Recent Posts Introduction':'灵感广场“最新帖文”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的帖文内容原文，支持主页选择器及帖文类型筛选，展示顺序由发帖时间由近及远为您展示，让您对海外社交媒体的最新新闻一目了然。',
	'inspiration_Hottest Posts Introduction':'灵感广场“最热帖文”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的帖文内容原文，支持主页选择器及帖文类型筛选，展示顺序依帖文互动量从多到少排序，让您对受粉丝欢迎的社交帖文一目了然。',
	'inspiration_Highly-Shared Posts Introduction':'灵感广场“分享意愿帖文”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的帖文内容原文，支持主页选择器及帖文类型筛选，引发“分享”动作更多的帖文，在这一列表中将被优先展示。经过OS评分海量数据分析发现，分享占比*超过3%的帖文更具有传播力。*分享占比 = 帖文分享数 / 帖文互动总数。',
	'inspiration_Extremely-Fun Posts Introduction':'灵感广场“积极情绪帖文”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的帖文内容原文，支持主页选择器及帖文类型筛选，引发用户表达“笑趴”情感更多的帖文，在这一列表中将被优先展示。经过OS评分海量数据分析发现，“笑趴”情绪占比*的比值超过1%的帖文更具有积极情绪效应，社交媒体粉丝对这类内容喜闻乐见。*笑趴情绪占比 = 帖文笑趴心情数 / 帖文心情总数。',
	'inspiration_Negative Posts Introduction':'灵感广场“消极情绪帖文”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的帖文内容原文，支持主页选择器及帖文类型筛选，引发用户表达“愤怒”情感更多的帖文，在这一列表中将被优先展示。经过OS评分海量数据分析发现，“愤怒”情绪占比*的比值超过1%的帖文更具有消极情绪效应，品牌主页运营者应对这一类型帖文有所警惕。*愤怒情绪占比 = 帖文愤怒心情数 / 帖文心情总数。',
	'inspiration_Recent video Introduction':'灵感广场“最新视频”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的视频内容，支持主页标签选择，展示顺序由发帖时间由近及远为您展示，让您对海外社交媒体的最新新闻一目了然。',
	'inspiration_Hottest video Introduction':'灵感广场“最多互动视频”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的视频内容，支持主页标签选择，展示顺序由视频所获的视频互动由多到少展示，让您对海外社交媒体的高质量视频一目了然。',
	'inspiration_Most Views video Introduction':'灵感广场“最多视频观看”瀑布流展示您关注的主页在所选时间段（默认值为近28天）所发布的视频内容，支持主页标签选择，展示顺序由视频所获的观看次数由多到少展示，让您对海外社交媒体的最热视频一目了然。',
	'inspiration_seekinspiration': '寻找灵感',
	'inspiration_SelectPageType_photo':"图片",
	'inspiration_SelectPageType_video':"视频",
	'inspiration_SelectPageType_status':"文字",
	'inspiration_SelectPageType_link':"链接",
	'inspiration_SelectPageType_IMAGE':"图片",
	'inspiration_SelectPageType_VIDEO':"视频",
	'inspiration_SelectPageType_carousel_album':"轮播图",
	'inspiration_SelectPageType_CAROUSEL_ALBUM':"轮播图",
	'inspiration_SelectPageType_youtube_post_created_time':"最新视频",
	'inspiration_SelectPageType_youtube_post_engagements':"最多互动视频",
	'inspiration_SelectPageType_youtube_view_count':"最多视频观看",
	'inspiration_SelectPageType_linkedin_post_created_time':"最新帖文",
	'inspiration_SelectPageType_linkedin_post_engagements':"最多互动帖文",
	'inspiration_postmain_facebook_post_engagements':'互动',
	'inspiration_postmain_facebook_post_likes':'心情',
	'inspiration_postmain_facebook_post_like_haha':'笑趴',
	'inspiration_postmain_facebook_post_like_angry':'愤怒',
	'inspiration_postmain_facebook_post_shares':'分享',
	'inspiration_postmain_facebook_post_comments':'评论',
	'inspiration_postmain_facebook_prefersharing':'分享意愿',
	'inspiration_postmain_facebook_Anger tendency':'愤怒倾向',
	'inspiration_postmain_facebook_LaughingTendency':'笑趴倾向',
	'inspiration_postmain_twitter_post_engagements':'互动',
	'inspiration_postmain_twitter_post_likes':'喜欢',
	'inspiration_postmain_twitter_post_shares':'转发',
	'inspiration_postmain_twitter_post_comments':'回复',
	'inspiration_postmain_instagram_post_engagements':'互动',
	'inspiration_postmain_instagram_post_likes':'点赞',
	'inspiration_postmain_instagram_post_comments':'评论',
	'inspiration_postmain_collected':'已收藏',
	'inspiration_postmain_Collection_post':'收藏帖文',
	'inspiration_postmain_Collection_Video':'收藏视频',
	'inspiration_postmain_youtube_view_count':"观看次数",
	'inspiration_postmain_youtube_post_likes':"顶",
	'inspiration_postmain_youtube_post_dislikes':"踩",
	'inspiration_postmain_youtube_post_comments':"评论",
	'inspiration_postmain_linkedin_post_engagements':"互动",
	'inspiration_postmain_linkedin_post_likes':"点赞",
	'inspiration_postmain_linkedin_post_comments':"评论",
	// 全球榜单-导航
	'globallist_facebook_list': 'Facebook榜单',
	'globallist_brand_list': '品牌榜单',
	'globallist_brand_total_list': '品牌总榜',
	'globallist_industry_brand_list': '行业品牌榜',
	'globallist_post_list': '帖文榜',
	'globallist_twitter_list': 'Twitter榜单',
	'globallist_instagram_list': 'Instagram榜单',
	'globallist_Top_20_China_Brand': '出海20强',
	'globallist_China_Brand_Top_20': '中国出海20强',
	'globallist_global_list': '全球榜单',
	// 全球榜单-中国出海20强
	'globallist_score': '品牌分',	
	// 全球榜单-品牌榜	
	'globallist_facebook_brand_list': 'Facebook品牌总榜',
	'globallist_twitter_brand_list': 'Twitter品牌总榜',
	'globallist_instagram_brand_list': 'Instagram品牌总榜',
	'globallist_daily_list': '日榜',
	'globallist_week_list': '周榜',
	'globallist_month_list': '月榜',
	'globallist_facebook_industry_brand_list': 'Facebook行业品牌榜',
	'globallist_twitter_industry_brand_list': 'Twitter行业品牌榜',
	'globallist_brand': '品牌',
	'globallist_contain_page_num': '包含主页数',
	'globallist_belong_to_industry': '所属行业',
	'globallist_fan': '粉丝',
	'globallist_brand_score': '品牌评分',
	'globallist_onesight_say': '品牌寄语',
	'globallist_onesight_say_text': '没有凭空的黑马，只是背后付出了更多的心血和汗水。',
	'globallist_spread_more': '展开更多',
	'globallist_scoring_mode': '榜单计分方式',
	// 全球榜单-评分详情
	'globallist_fans_score': '粉丝数得分',
	'globallist_fans_diff_score': '新增粉丝得分',
	'globallist_post_score': '发帖数得分',
	'globallist_post_engagement_score': '帖文互动得分',
	'globallist_thousand_people_engagement_score': '千人互动得分',
	// 全球榜单-行业选择器
	'globallist_all_industry': '全部行业',
	'globallist_back': '返回',
	'globallist_all': '全部',
	'globallist_industry': '行业',
	'globallist_please_choose_industry': '请选择行业',
	// 全球榜单-主页列表
	'globallist_homepage': '主页',
	'globallist_country': '国家',
	'globallist_homepage_link': '主页链接',
	'globallist_homepage_score': '主页评分',
	'globallist_attention': '添加至分析列表',
	// 全球榜单-提名入榜
	'globallist_nominate': '提名入榜',
	'globallist_enter_your_homepage_information': '请输入您想添加的主页信息',
	'globallist_page_link': '主页链接',
	'globallist_market_oriented': '面向市场',
	'globallist_subordinate_brand': '所属品牌',
	'globallist_brand_country': '品牌国家',
	'globallist_chinese_brand': '中国品牌' ,	
	'globallist_subordinate_industry': '所属行业',
	'globallist_nominate_reason': '提名理由',
	'globallist_nominate_confirm': '确定',
	'globallist_nominate_search': '搜索',
	'globallist_nominate_submit': '提交',
	'globallist_nominate_cancel': '取消',
	'globallist_nominate_edit': '编辑',
	'globallist_input_page_link_tip': '请输入主页链接！',
	'globallist_confirm_page_link_tip': '请确认主页链接！',
	'globallist_input_country': '请选择国家',
	'globallist_input_country_tip': '请选择国家！',
	'globallist_input_brand_name': '请输入品牌名称',
	'globallist_input_brand_name_tip': '请输入品牌名称！',
	'globallist_choose_industry': '请选择行业',
	'globallist_choose_industry_tip': '请选择行业！',
	'globallist_submit_success': '提交成功！感谢您的建议！',
	'globallist_continue_follow_list': '请继续关注榜单！',
	// 全球榜单-帖文榜
	'globallist_facebook_postlist': 'Facebook帖文榜',
	'globallist_twitter_postlist': 'Twitter帖文榜',
	'globallist_instagram_postlist': 'Instagram帖文榜',
	'globallist_post_language': '帖文语言：',
	'globallist_english': '英文',
	'globallist_chinese': '中文',
	'globallist_post_interaction': '帖文互动',
	'globallist_interaction': '互动',
	'globallist_post_performance': '帖文表现',
	'globallist_positive_mood': '积极心情',
	'globallist_sharing': '分享意愿',
	'globallist_haha': '笑趴心情',
	'globallist_angry': '愤怒心情',
	'globallist_proportion_of_interaction': '占互动比',
	'globallist_exceed': '超过',
	'globallist_post': '帖文',
	'globallist_post_has_no_text': '此帖文暂无文字',
	'globallist_share_is_the_best': '分享意愿超高！',
	'globallist_can_you_be_funnier': '高能搞笑，引起互动！',
	'globallist_good_words_worth_a_million': '好内容能带来好口碑！',
	'globallist_negative_event_deal_with_it': '负面事件，不处理可不行!',
	'globallist_top_100_posts': '全网帖文热度前100！',
	// 公共汉化
	'onesight': '一网互通',
	'aboutus': '关于我们',
	'addpage':'添加主页',
	'disclaimer':'免责申明',
	'search':'搜索',
	'global': '全球',
	'common_to':'至',
	'common_day':'天',
	'common_hour':'小时',
	'common_fans':'粉丝',
	'common_select_list_placeholder':'输入关键字',
	'common_search':'搜索',
	'common_single':'个',
	'common_analysis_title_tip':'通过点击主页，进入主页详情，详细了解主页数据！',
	'common_usercolor_nofill':'无填充',
	'common_deltile':'确定删除吗?',
	'common_deltile_btn_sure':'确定',
	'common_deltile_btn_sures':'确定',
	'common_deltile_btn_Add':'添加',
	'common_deltile_btn_cancel':'取消',
	'common_deltile_btn_cancels':'取消',
	'common_emptylist_title_left':'现在，添加一个',
	'common_emptylist_title_right':'主页',
	'common_search_null':'暂未搜索到相关主页',	
	'common_post_noData':'暂无帖文',
	'common_noData':'暂无数据',
	'YoutubeVideo_common_noData':'所选日期范围内\n无新增视频',
	'YoutubeLike_common_noData':'所选日期范围内\n无新增视频',
	'YoutubeVideoEngagement_common_noData':'所选日期范围内\n无新增视频',
	'common_changeauthData':'切换为授权数据',
	'common_changepubData':'切换为公开数据',
	'common_View_Details':'查看详情',
	'common_Load_More': '加载更多',
	'common_Return_platform': '返回平台',
	//时间控件
	'OSDateRangePicker_yesterday':'昨天',
	'OSDateRangePicker_last_7_days':'近7天',
	'OSDateRangePicker_last_28_days':'近28天',
	'OSDateRangePicker_last_90_days':'近90天',
	'OSDateRangePicker_last_week':'上周',
	'OSDateRangePicker_last_month':'上月',
	'OSDateRangePicker_selected':'已选',
	'OSDateRangePicker_Mon':'一',
	'OSDateRangePicker_Tues':'二',
	'OSDateRangePicker_Wed':'三',
	'OSDateRangePicker_Thur':'四',
	'OSDateRangePicker_Fri':'五',
	'OSDateRangePicker_Sat':'六',
	'OSDateRangePicker_Sun':'日',
	// 素材库
	'MyFavorite_Favorite_post':'我的素材库',
	'MyFavorite_NO_Favorite':'您还没有收藏任何帖文，您可以在帖文列表、帖文详情页进行收藏。',
	'MyFavorite_Recent':'最新收藏',
	'MyFavorite_Seven':'最近7天',
	'MyFavorite_TwentyEight':'最近28天',
	'MyFavorite_All':'全部收藏',
	'MyFavorite_link':'链接',
	'MyFavorite_photo':'图片',
	'MyFavorite_VIDEO':'视频',
	'MyFavorite_video':'视频',
	'MyFavorite_status':'文字',
	'MyFavorite_IMAGE': '图片',
	'MyFavorite_CAROUSEL_ALBUM': '轮播图',
	'MyFavorite_event':'',	
	'MyFavorite_Favorited':'收藏于',
	//帖文详情弹框
	'postDetailPopup_basedata':'基础数据',
	'postDetailPopup_basedata_mood':'心情',
	'postDetailPopup_basedata_engagement':'互动',
	'postDetailPopup_basedata_share':'分享',
	'postDetailPopup_basedata_comments':'评论',
	'postDetailPopup_emotionAnal':'情感分析',
	'postDetailPopup_emotionAnal_positive':'积极情绪',
	'postDetailPopup_emotionAnal_passive':'消极情绪',
	'postDetailPopup_authdata':'授权数据',
	'postDetailPopup_authdata_impressions':'曝光',
	'postDetailPopup_authdata_impressions_organic':'自然曝光',
	'postDetailPopup_authdata_impressions_paid':'付费曝光',
	'postDetailPopup_authdata_impressions_fan':'对粉丝曝光',
	'postDetailPopup_authdata_impressions_unfan':'对非粉丝曝光',
	'postDetailPopup_authdata_clicks':'总点击',
	'postDetailPopup_authdata_clicks_photo':'图片点击',
	'postDetailPopup_authdata_clicks_video':'视频点击',
	'postDetailPopup_authdata_clicks_link':'链接点击',
	'postDetailPopup_authdata_clicks_other':'其他点击',
	'postDetailPopup_authdata_negative_feedback':'消极操作',
	'postDetailPopup_authdata_negative_feedback_hide':'隐藏',
	'postDetailPopup_authdata_negative_feedback_hideall':'隐藏所有',
	'postDetailPopup_authdata_negative_feedback_unlike':'取消赞',
	'postDetailPopup_authdata_negative_feedback_report':'举报',
	'postDetailPopup_applyfor':'对当前视频开启“下载素材”申请。提出申请后，OS平台将对这一视频素材进行入库及内容同步，24小时内即可在OS平台查看视频全片。这一功能将依用量收费，了解更多请查看“',
	'postDetailPopup_applyfor_open':'增长工具',
	'postDetailPopup_lifetime':'对当前帖文开启“帖文生命周期”功能，成功开启后，OS平台即将对当前帖文开启每小时抓取帖文互动数并绘制成未来7天趋势图。',
	'postDetailPopup_lifetime_open':'开启生命周期',
	'postDetailPopup_lifetime_period':'帖文生命周期',
	'postDetailPopup_post_goopen':'去',
	'postDetailPopup_post_open':'打开帖文',
	'postDetailPopup_video_open':'打开视频',
	'postDetailPopup_previous': '上一页',
	'postDetailPopup_next': '下一页',
	// 常见问题解答
	'common_problem':'常见问题',
	'common_problem_contact_we':'联系我们',
	'common_problem_contact_faq':'商家主页转换',
	'common_problem_explain':'常见问题在这里，您想要的所有解决方案',
	//twitter 主页详情
	//twitter 粉丝
	"twitter_pagedetail_chart_title_Fans":'粉丝',
	'twitter_pagedetail_trend_table_line_CurrentFansNum':'当前粉丝数',
	'twitter_pagedetail_trend_table_line_MaxPerDayFansNum':'最大单日粉丝数',
	'twitter_pagedetail_trend_table_line_MinPerDayFansNum':'最小单日粉丝数',
	"twitter_pagedetail_chart_title_FansGrowth":'粉丝增长',
	'twitter_pagedetail_trend_table_line_TotalFansNum':'总计粉丝增长数',
	'twitter_pagedetail_trend_table_line_MaxPerDayFansGrowthNum':'最大单日粉丝增长数',
	'twitter_pagedetail_trend_table_line_MinPerDayFansGrowthNum':'最小单日粉丝增长数',
	'twitter_pagedetail_trend_table_line_AvgPerDayFansGrowthNum':'平均单日粉丝增长数',
	'twitter_pagedetail_chart_title_FansGrowthAndPostEngagement':"粉丝增长及帖文互动",
	'twitter_pagedetail_trend_table_line_MaxFansChange':'最大粉丝变化',
	'twitter_pagedetail_trend_table_line_MaxFansChangeCurrentDayEngagement':'最大粉丝变化当日互动',
	"twitter_pagedetail_chart_title_interactive":'活跃粉丝 TOP50',
	"twitter_pagedeilte_Top 50 Interacted Fans_cont":'在所选时间范围内，与主页互动次数排名前 50 的粉丝。',
	'twitter_fanspagetableTitle_rank':'排名',
	'twitter_fanspagetableTitle_user':'用户',
	'twitter_fanspagetableTitle_Interact_with_me':'与我互动',
	'twitter_fanspagetableTitle_shares_me':'转发我',
	'twitter_fanspagetableTitle_comments_me':'转发我',
	'twitter_fanspagetableTitle_@_me':'转发我',
	'twitter_fanspagetableTitle_fansTa':'Ta的粉丝',
	"tooltip_text":'文字',
	"pagedetail_chart_title_Proportion of Interactions of Posts by Posts's Type":'各类帖文所获互动（按类型）',
	"pagedetail_chart_title_postType":'帖文类型',
	"pagedetail_chart_title_postNum":'发帖数量',
	"pagedetail_chart_title_postEngagement":'所获帖文互动',
	"pagedetail_chart_title_postEngagementRatio":'帖文互动占比',
	// 增长工具
	'IncreaseTool_All':'增长工具',
	'IncreaseTool_DowloadHistory':'导出报告管理',
	'IncreaseTool_EmotionAnalysis':'评论情绪分析',
	'IncreaseTool_EmotionAnalysis_Info':'语义情感分析在社交媒体管理上有很多的应用场景，比如管理一个电商主页，卖家需要时刻关心用户对于商品的评论是否是正面的。再比如做一个新产品海外上市的宣传和策划，这一单品在社交媒体上的评论对后续市场投入至关重要。社交媒体上的热门帖文都可能产生成千上万的文本评论，#CommentSenti工具通过云端自然语义能力，以单一帖文为切入点分析舆论走向与点评核心。',
	'IncreaseTool_DownloadPDF':'导出报告',
	'IncreaseTool_Publisher':'帖文发布工具',
	'IncreaseTool_DownliadHist':'导出报告管理',
	'IncreaseTool_DownloadPDF_Info':'及时一致的报告体系对社交媒体管理至关重要。对于一个全球品牌管理者，一次性达成全球市场的报告是运营上的巨大挑战。OneSight自动报告导出功能为您完成一次性批量报告生成，数据来源及展示方式与站内保持一致，支持csv及PDF两种格式，7类关键数据维度自由选择，更支持产品化定制。目前支持模板包括：',
	'IncreaseTool_DownloadPDF_somelTitle_one':'主页运营报告（纯数据报告）',
	'IncreaseTool_DownloadPDF_somelTitle_two':'主页帖文运营报告（数据+内容报告）',
	'IncreaseTool_DownloadPDF_somelTitle_three':'行业竞争品牌报告（多品牌数据整合报告）',
	'IncreaseTool_TagCount':'标签统计',
	'IncreaseTool_Data_Tip':'我们将于24小时之内与您联系，节假日可能顺延，感谢您的等待。',
	'IncreaseTool_In_audit':'审核中',
	'IncreaseTool_Use_Application':'使用申请',
	'IncreaseTool_look_examplePDF':'查看范例',
	'IncreaseTool_EmotionAnalysis_BottomInfo':'语义情感分析在社交媒体管理上有很多的应用场景，比如管理一个电商主页，卖家需要时刻关心用户对于商品的评论是否是正面的。再比如做一个新产品海外上市的宣传和策划，这一单品在社交媒体上的评论对后续市场投入至关重要。社交媒体上的热门帖文都可能产生成千上万的文本评论，#CommentSenti工具通过云端自然语义能力，以单一帖文为切入点分析舆论走向与点评核心。',
	'IncreaseTool_DownloadPDF_BottomInfo':'OneSight自动报告导出功能为您完成一次性批量报告生成，数据来源及展示方式与站内保持一致，支持csv及PDF两种格式，7类关键数据维度自由选择，更支持产品化定制。目前支持模板包括：',
	'IncreaseTool_DownloadPDF_BottomInfo_list_1':'主页运营报告（纯数据报告）',
	'IncreaseTool_DownloadPDF_BottomInfo_list_2':'主页帖文运营报告（数据+内容报告）',
	'IncreaseTool_DownloadPDF_BottomInfo_list_3':'行业竞争品牌报告（多品牌数据整合报告）',
	'IncreaseTool_Release_BottomInfo':'发布工具能满足您在海外社交平台发布帖文的需求。主页授权、发布内容、查看已发帖文数据，一站式服务让您轻松在海外平台上发声。',
	'IncreaseTool_Release_BottomInfo_list_1':'设置发帖时间：高效安排您的发布计划',
	'IncreaseTool_Release_BottomInfo_list_2':'帖文预览：让你体验原汁原味的帖文状态',
	'IncreaseTool_Release_BottomInfo_list_3':'查看帖文详情：让您直观了解帖文的数据情况',
	'IncreaseTool_Release_BottomInfo_list_4':'目前支持的海外社交平台为Facebook、Twitter',
	//twitter// 互动
	'pagedetail_trend_table_line_MaxEngagementPost':"所获最多互动帖文类型",
	'pagedetail_trend_table_line_MinEngagementPost':"所获最少互动帖文类型",
	//Dashboard 
	"Dashboard_postEngagement":'帖文互动',
	"Dashboard_post":'帖文',
	"Dashboard_fansDiff":'粉丝增长',
	"Dashboard_fans":'粉丝',
	'Dashboard_postEnaggement_num':'帖文互动数',
	"Dashboard_title_welcome":'欢迎来到 OneSight 出海营销云--品牌全球孵化器。',
	"Dashboard_Data":'您所使用的 OS 平台功能',
	"Dashboard_Following_pages":'正在关注主页',
	"Dashboard_Following_posts":'已收藏帖文',
	"Dashboard_Paid_Services":'正在使用付费服务',
	"Dashboard_DataOverview":'使用看板模式，查看主页数据总览',
	"Dashboard_TimeLook":'当前查看',
	'Dashboard_28TimeData':'近28天趋势表现',
	"Dashboard_echarts_title":'运营核心数据',
	"Dashboard_Description_fans":'粉丝的变化是主页运营状态最好的证明！',
	"Dashboard_Description_fansDIff":'粉丝增长的变化可以直观的了解粉丝的变化！',
	"Dashboard_Description_post":'发帖是增粉的基础！',
	"Dashboard_Description_post_engagement":'帖文互动可以直观的了解帖文受众的反应！',
	"Dashboard_flover_page":'前往数据分析定量管理主页数据',
	"Dashboard_flover_Post":'前往内容灵感发现更多精彩帖文',
	"Dashboard_flover_Paid":'前往增长工具发现更多高效营销工具',
	"Dashboard_goNow":'前往',
	"Dashboard_Go to Page Details":'前往主页详情，查看更多数据',
	'Dashboard_yearsToday':'昨日关键数据表现',
	"Dashboard_err_NoAuth":'请前往Facebook授权，方可开启授权模版数据',
	"Dashboard_err_ThreePage":'必须选择三个页面来导出竞品报告',
	"Dashboard_err_SaveBtn":'竞品组合尚未确认，请保存更改',
	"Dashboard_err_PageAuth":'需要对主页授权后，才可导出授权数据报告',
	"Dashboard_err_Pay":'付费后使用',
	"Dashboard_err_30PageNum":'PDF单次最多可导出30条帖文',
	'Dashboard_err_Number':'请输入数字',
	"Dashboard_SelectPage":'选择主页',
	"Dashboard_SavePage":'保存设置',
	"Dashboard_SaveSuccess":'保存成功',
	//change Info
	"ChangeInfo_title":'账号信息',
	"ChangeInfo_Name":'账号信息',
	"ChangeInfo_Company":'企业名称',
	"ChangeInfo_industry":'所在行业',
	"ChangeInfo_Phone":'手机',
	"ChangeInfo_Email":'邮箱地址',
	"ChangeInfoReport_an_error_Name":'请输入您的真实姓名，以便于我们为您提供更好的服务。',
	"ChangeInfoReport_an_error_Company":'请输入您的企业名称，以便于我们提供更精准的服务。',
	"ChangeInfoReport_an_error_industry":'请选择您/企业所在行业，以便于我们提供定制化的服务。',
	"ChangeInfo_Save":'保存',
	//授权
	"auth_Connect_Facebook_Insights":'获取授权',
	"auth_weNeedauthorization":'获取该主页的Insights数据，需要您的授权。',
	"auth_NotNow":'暂不授权',
	"auth_Connect Facebook Insights":'去Facebook授权',
	"auth_not Connect":'无法授权',
	"auth_notFacebookauth":'您在Facebook上登录的账号不具备该主页Insights数据的授权权限',
	"auth_Try Later":'暂不授权',
	'auth_need_connect':'如果您是该主页的所有者，登陆facebook账号然后进行授权，即可查看更长时间段跨越度，也可以查看包括粉丝画像、粉丝在线时长及粉丝地区分布情况等更多维度的数据。（注释：该授权数据仅您自己可以看到。）',
	'auth_need_connect_now':'现在授权',
	'auth_need_connect_ok':'授权成功',
	'auth_ok':'完成',
	// 申请演示表格
	"FormTable_Request_Demo_Form":"申请试用",
	"FormTable_Applicant_Name":"申请人姓名",
	"FormTable_Company_Name":"申请人公司",
	"FormTable_Department":"申请人部门",
	"FormTable_Position":"申请人职位",
	"FormTable_Tel_No":"申请人电话",
	"FormTable_Email_Address":"申请人邮箱",
	"FormTable_Industry":"所属行业",
	"FormTable_Button":"提 交",
	// 申请演示表格错误信息
	"FormTable_err_real_name":"请输入真实姓名",
	"FormTable_err_company_name":"请输入公司名",
	"FormTable_err_department":"请输入部门",
	"FormTable_err_position":"请输入职位",
	"FormTable_err_accept_numbers":"电话号码必须由数字组成",
	"FormTable_err_Email_address":"请输入邮箱",
	"FormTable_err_industry":"请选择一个行业",
	// 选择行业
	"FormTable_select_industry": "请选择行业",
	// 评论情感分析功能
	"ChargeTool_CommentSenti_Analytics":"评论情感分析功能",
	"ChargeTool_Function_left":"工具功能",
	"ChargeTool_Function_right":"语义分析",
	"ChargeTool_Platform_left":"工具适用平台",
	"ChargeTool_Platform_right":"Facebook",
	"ChargeTool_Area_left":"工具适用范围",
	"ChargeTool_Area_right":"Facebook帖文评论",
	"ChargeTool_Language_left":"适用语言",
	"ChargeTool_Language_right":"英语",
	"ChargeTool_Pricing_left":"计费方式",
	"ChargeTool_Pricing_right":"依用量定价",
	"ChargeTool_View_Sample":"查看范例",
	"ChargeTool_Request_Demo":"申请演示",
	// 提交成功信息
	"ChargeIndex_success_top":"您的申请已成功提交。",
	"ChargeIndex_success_bottom":"稍后OneSight专业人员将通过以上信息联系您，请保持电话畅通。",
	//添加页面facebook授权
	'Pleace_add_facebook_page':'从以下主页中，打勾选中添加至OneSight数据分析平台：',
	'add_page':'共添加',
	'add_page_list':'个主页进入您的OneSight主页列表',
	'add_page_lists':'个主页进入您的OneSight主页列表',
	// 导出报告
	'ChargeDownloadPDF_Export_Report':'运营导出报告功能',
	'ChargeDownloadPDF_Functions':'功能特权',
	'ChargeDownloadPDF_Free_Trial':'免费试用版',
	'ChargeDownloadPDF_SME_Solution_top':'中小企业',
	'ChargeDownloadPDF_SME_Solution_bottom':'解决方案',
	'ChargeDownloadPDF_Brand_Solution_top':'品牌',
	'ChargeDownloadPDF_Brand_Solution_bottom':'解决方案',
	'ChargeDownloadPDF_Request_Demo':'申请试用',
	'ChargeDownloadPDF_Request_Go_Now':'立即前往',
	'ChargeDownloadPDF_Key_Metrics':'数据维度',
	'ChargeDownloadPDF_6':'6个',
	'ChargeDownloadPDF_16':'16个',
	'ChargeDownloadPDF_for_with_or_without_authorization':'授权及非授权数据',
	'ChargeDownloadPDF_Monthly_Downloads':'月度下载',
	'ChargeDownloadPDF_3_Downloads':'3次',
	'ChargeDownloadPDF_Unlimited':'不限',
	'ChargeDownloadPDF_No_of_Users':'用户数',
	'ChargeDownloadPDF_1_user':'1个',
	'ChargeDownloadPDF_5_user':'5个',
	'ChargeDownloadPDF_10_user':'10个',
	'ChargeDownloadPDF_Export_PDF':'导出PDF版本',
	'ChargeDownloadPDF_Export_Excel':'导出Excel版本',
	'ChargeDownloadPDF_Export_Word':'导出Word版本',
	'ChargeDownloadPDF_6_Available_Templates':'6个可选模板',
	'ChargeDownloadPDF_Customized_Templates':'申请定制模板',
	//新手指导
	'new_welcome':"欢迎使用",
	'new_oneStop':"您的一站式品牌出海平台",
	'new_step':'是海外社交媒体数据营销工具，可以为您监控海外社交媒体主页。',
	'new_use':'我们为您准备了一份简单的引导，便于您更快地上手使用。',
	'new_not':'暂不需要',
	'new_Go':'开始引导',
	'new_ok':'完成',
	'new_helping':'我们仍期待为您提供帮助！',
	'new_wechat':'产品使用中如有任何问题及意见请添加客服微信。',
	'new_time':'扫一扫，添加您的24小时微信客服。',
	'new_first_title':'使用OneSight添加关注主页',
	'new_first_subtitle':'在 OneSight 添加关注的主页后，就可以每日查看关注主页的数据 变化，进行定量分析。 ',
	'new_first_cont_one':'支持 Facebook/Twitter/Instagram 三大主流海外社交媒体平台',
	'new_first_cont_two':'针对主页、帖文、粉丝、帖文互动共计数据纬度百余项',
	'new_first_cont_three':'支持批量添加主页',
	'new_first_goto':'前往',
	'new_first_can':'即可添加主页 ！',
	'new_secound_title':'收藏帖文至我的素材库',
	'new_secound_subtitle':'收藏的帖文将存于您的素材库中，为日后发布有趣的帖文做准备！',
	'new_secound_cont_one':'收藏帖文互动最高的帖文',
	'new_secound_cont_two':'收藏节假日前后有助于热点营销的帖文',
	'new_secound_cont_three':'收藏带给您灵感的帖文',
	'new_secound_goto':'前往',
	'new_secound_can':'即可收藏更多精彩帖文 ！',
	'new_third_title':'使用有价值的付费服务',
	'new_third_subtitle':'您在 OS 中使用的付费功能将被统计于此，OS 目前提供了多种有价值的付费服务。',
	'new_third_cont_one':'帖文评论情绪分析',
	'new_third_cont_two':'导出 PDF、行业趋势报告',
	'new_third_cont_three':'主页标签分析',
	'new_third_goto':'前往',
	'new_third_can':'发现更多高效增长营销工具 ！',
	'new_fourth_title':'核心数据看板',
	'new_fourth_subtitle':'当您成功添加主页后，可以使用看板模式来迅速监测每日主页核心数据变化。',
	'new_fourth_cont_one':'点击右侧主页选择器可以更换主页。',
	'new_fourth_cont_two':'点击下方前往主页详情按钮可查看该主页的更多数据。',
	'new_fifth_title':'完成引导',
	'new_fifth_subtitle':'您已完成所有引导',
	'new_fifth_goto':'赶紧开始您畅快的出海营销之旅吧！！！',
	'new_fifth_cont_one':'您可以凭此截图，扫码添加微信客服领取红包哦 ！',
	'new_fifth_ok':'开始',
	//导出PDF
	AlertPDf_title:'导出运营报告',
	AlertPDf_title_small:'一键导出运营数据，数据概览一目了然',
	AlertPDf_main_Industry:'行业',
	AlertPDf_main_TargetIng:'目标市场',
	AlertPDf_main_Select_RePort_type:'选择报告类型',
	AlertPDf_main_Select_RePort_Format:'选择文件格式',
	AlertPDf_main_EcportDataInclude:'导出数据项',
	AlertPDf_main_RePort_Time:'报告日期',
	AlertPDf_main_ExPort:'导出报告',
	AlertPDf_footer_Am:'我是主页管理员',
	AlertPDf_footer_Data:'获取更多数据洞察',
	AlertPDf_footer_auth:"点击授权",
	AlertPDf_ExportType_Operational:"主页运营报告",
	AlertPDf_ExportType_post:"主页帖文报告",
	AlertPDf_ExportType_OperationalAuth:"主页运营报告（授权）",
	AlertPDf_ExportType_postAuth:"主页帖文报告（授权）",
	AlertPDf_ExportType_FanPortraitAuth:"粉丝画像报告（授权）",
	AlertPDf_ExportType_Competitive:"竞品跟踪报告",
	AlertPDf_ExportType_DownNum:"本月下载报告数量记录",
	AlertPDf_ExportType_frequency:"次",
	AlertPDf_ExportType_HistoryExport:"查看历史报告",
	AlertPDf_ExportType_AdvisoryService:"咨询客服",
	AlertPDf_ExportType_ErrorNotAuth:"需要对主页授权后，才可导出授权数据报告",
	AlertPDf_ExportType_ErrorNotpayment:"付费后使用",
	AlertPDf_ExportType_Add1page:"添加第一个主页",
	AlertPDf_ExportType_Add2page:"添加第二个主页",
	AlertPDf_ExportType_Add3page:"添加第三个主页",
	AlertPDf_ExportType_SelectExportRange:"选择导出范围",
	AlertPDf_ExportType_SelectTimePostNum:"选中范围内帖文总数",
	AlertPDf_ExportType_article:"条",
	AlertPDf_ExportType_ExportAll:"导出全部",
	AlertPDf_ExportType_ExportNum:"导出第",
	AlertPDf_ExportType_ExportTo:"条至第",
	//Export PDF
	Export_title:"导出报告管理",
	Export_title_time:"有效期至",
	Export_title_money:"续费",
	Export_main_title:"历史导出报告记录（近30天）",
	Export_main_Numbering:"编号",
	Export_main_ReportTopic:"报告主题",
	Export_main_format:"格式",
	Export_main_BuildDate:"生成日期",
	Export_main_operating:"操作",
	Export_main_loading:"下载",
	Export_footer_moreanswer:"还有更多问题？",
	Export_footer_left:"1.在微信“添加好友”中，搜索我们的客服微信号：OneSightSupport",
	Export_footer_leftnswer:"2.备注您的信息为：付费服务支持 ，之后提出您的问题即可",
	Export_footer_small:"*我们的客服可能会向您核对您的OneSight账户信息，提供与注册资料一致的电话号码或邮箱地址即可",
	Export_footer_scan_it:"扫码添加微信客服",
	Export_prompt:"请前往Facebook授权，方可开启授权模版数据",
	// InsAuthorize Ins主页转化为商家主页
	'InsAuthorize_header':'Facebook 主页关联到 Instagram 业务帐户详细步骤指引',
	'InsAuthorize_Instagram_API':'由于 Facebook 官方限制，Instagram 商家账户必须与 Facebook 公共主页关联， 才能够使用 Instagram API;',
	'InsAuthorize_step':'步骤如下',
	'InsAuthorize_step_one':'进入自己的 Facebook 账号中已创建的公共主页(公共主页，非您自己的 Facebook 首页，如果没有您需要先创建一个 Facebook 公共主页)。',
	'InsAuthorize_step_two':'进入公共主页，点击“设置”。',
	'InsAuthorize_step_three':'进入设置页面后，然后点击常规选项中的“Instagram”。',
	'InsAuthorize_step_fore':'点击“登录”，登录您想要添加至 OneSight 主页列表的 Instagram 帐号。',
	'InsAuthorize_step_five':'成功登录后，会出现“设置商家主页”弹窗，点击继续，并完善您想在 Instagram 商家主页上显示的基本信息。填写完成后，点击完成即成功绑定。',
	'InsAuthorize_step_sex':'成功关联成功后，就可以在 OneSight 添加该 Instagram 主页了。',
	//Download
	'Download_page_success':'报告导出成功',
	'Download_page_closeWindow':'关闭窗口',
	'Download_page_AginPDF':'重新导出报告',
	'Download_page_Error':'报告导出失败',
	'Download_page_Time':'报告努力制作中，大约需要 1 分钟。',
	'Download_page_NOcloseWindow':'请不要关闭此页面',
	'Download_page_UnderReview':'您的申请正在审核中，请耐心等待',
	'Download_page_UnderReviewBtn':'我知道了',
	// 对比
	'start_compare': '开启对比',
	'cancel_compare': '取消对比',
	'a_period': 'A组',
	'b_period': 'B组',
	// 绑定第三方账号
	'bound_accounts': '已绑定账号',
	'bind_remove': '移除',
	'bind_account': '绑定其他第三方账户',
	'only_bind_one_facebook_account': '每个账号只能绑定一个facebook平台账号，若您想绑定新的facebook账号，请先将已绑定账号移除',
	'only_bind_one_twitter_account': '每个账号只能绑定一个twitter平台账号，若您想绑定新的twitter账号，请先将已绑定账号移除',
	'only_bind_one_linkedin_account': '每个账号只能绑定一个linkedin平台账号，若您想绑定新的linkedin账号，请先将已绑定账号移除',
	'remove_account_content': '移除第三方账号绑定后，无法继续使用该账号进行第三方账号登录，确定移除该账号吗？',
	'bound_by_other_account_title': '已被另一个OneSight账号绑定',
	'bound_by_other_account_content': '出于安全原因，每个社交主页只能绑定一个OneSight账号。请检查您是否使用其它账号进行了授权，如果仍有疑问，请联系客服人员，客服电话010-85818058。',
	// linkedin-主页详情
	'pagedetail_aboutus': '关于我们',
	'pagedetail_company_size': '公司规模',
	'pagedetail_company_specialties': '专注领域',
	// linkedin-主页详情-招聘数趋势
	'pagedetail_recruitment_trend': '招聘数趋势',
	'pagedetail_trend_table_line_CurrentRecruitmentNumber': '当前招聘数',
	'pagedetail_trend_table_line_MaxPerDayRecruitNum':'最大单日招聘数',
	'pagedetail_trend_table_line_MinPerDayRecruitNum':'最小单日招聘数',
	// linkedin-主页详情-招聘数趋势-悬浮框
	'tooltip_recruitment_trend': '主页在 LinkedIn 平台上发布的职位数。',
	// linkedin-主页详情-招聘数趋势-右侧tip
	'tip_recruitment_trend': '主页在 LinkedIn 平台上发布的职位数。',
	// linkedin-主页详情-在线员工数趋势
	'pagedetail_recruitment_peopleNum': '在线员工数趋势',
	'tip_recruitment_peopleNum': '主页在 LinkedIn 平台上已有的员工数量',
	'tooltip_recruitment_peopleNum': '主页在 LinkedIn 平台上已有的员工数量',
	'pagedetail_trend_table_line_CurrentpeopleNum': '当前在线员工数',
	'pagedetail_trend_table_line_MaxpeopleNum':'最大在线员工数',
	'pagedetail_trend_table_line_MinpeopleNum':'最小在线员工数',
	'pagedetail_trend_table_line_MostPopularPost': '最受欢迎帖文',
	'pagedetail_trend_table_line_MostUnpopularPost': '最不受欢迎帖文',
	'pagedetail_asterisk_tip': '*意味着这一数据的准确性可能会受到系统及Linkedin稳定性影响，可联系我们的客服进行人工核实及更正。',
	"AddPage_linkedIn_padding":"添加成功，OS正为您加载数据中...",
	"AddPage_linkedIn_NoHaveFont":"您输入的链接中需要包含/company，例如：https://www.linkedin.com/company/onesighttech/",
	"AddPage_linkedIn_NoHavePage":"OS在 LinkedIn 中并未找到对应的公司主页，请点击删除后重新添加。",
	"AddPage_linkedIn_AddPageAgin":"您已添加过该主页。",
	"AddPage_linkedIn_AddPageCount":"Linkedin数据分析对免费用户仅支持添加2个品牌。",
	"AddPage_linkedIn_EntryLink":"输入您想添加的主页链接...",
	"AddPage_linkedIn_BtnDataPadding":"数据加载中",
	"AddPage_linkedIn_BtnDelete":"删除",
	"AddPage_linkedIn_BtnAddPage":"添加",
	"AddPage_linkedIn_AddSomePageCallMy":"如您需要添加更多 LinkedIn 主页，请于产品右上角添加客服微信或拨打010-85818058与我们联系。",
	//linebarchart smalltext
	'Small_engagements':'次互动',
	"common_now_noData":"没有更多数据了",
	// 增长工具新增弹窗
	"IncreaseTool_add_Img_Info_title": "您的申请已审批通过",
	"IncreaseTool_add_Img_Info_PayReminderWrapIN": "可进入",
	"IncreaseTool_add_Img_Info_PayReminderWrapAnalytics": "数据分析",
	"IncreaseTool_add_Img_Info_PayReminderWrapDefilt": "主页详情",
	"IncreaseTool_add_Img_Info_PayReminderWrapPDF": "导出报告",
	"IncreaseTool_add_Img_Info_PayReminderWrapGo": "进行导出报告",
	"IncreaseTool_add_Img_Info_Page": "主页",
	"IncreaseTool_add_Img_Info_Download": "导出报告",
}
export default zh_CN;
	
// 使用方法
// {this.props.intl.formatMessage({id:"common_to",defaultMessage:"common_to"})}

// auth.state.getDataUrl+'/image?token='+auth.token()+'&url='+encodeURIComponent(v.post_image)